//
//  ClopApp.swift
//  Clop
//
//  Created by Alin Panaitiu on 16.07.2022.
//

import SwiftUI

import Atomics
import Cocoa
import Combine
import Defaults
import Foundation
import Ignore
import Lowtech
import LowtechIndie
import LowtechPro
import LowtechProSentry
import os
import Sentry
import ServiceManagement
import System
import UniformTypeIdentifiers

private let log = Logger(subsystem: LOG_SUBSYSTEM, category: "ClopApp")

func clopDebugLog(_ message: String, includeCallStack: Bool = false) {
    guard let bid = Bundle.main.bundleIdentifier, bid.hasPrefix("com.lowtechguys.Clop") else { return }

    let df = DateFormatter()
    df.dateFormat = "yyyy-MM-dd HH:mm:ss.SSS"
    var line = "[\(df.string(from: Date()))] \(message)\n"
    if includeCallStack {
        line += Thread.callStackSymbols.joined(separator: "\n") + "\n"
    }
    let path = (NSHomeDirectory() as NSString).appendingPathComponent(".clop-debug-logs")
    if let handle = FileHandle(forWritingAtPath: path) {
        handle.seekToEndOfFile()
        handle.write(line.data(using: .utf8)!)
        handle.closeFile()
    } else {
        FileManager.default.createFile(atPath: path, contents: line.data(using: .utf8)!)
    }
}

var pauseForNextClipboardEvent = false

class WindowManager: ObservableObject {
    @Published var windowToOpen: String? = nil

    func open(_ window: String) {
        windowToOpen = window
    }
}
let WM = WindowManager()

var TRANSIENT_TYPES: Set<NSPasteboard.PasteboardType> = [
    .init("org.nspasteboard.TransientType"),
    .init("org.nspasteboard.ConcealedType"),
    .init("org.nspasteboard.AutoGeneratedType"),
]

extension NSPasteboard {
    func debug() {
        #if DEBUG
            print(name.rawValue)
            guard let pasteboardItems else {
                print("No items")
                return
            }
            for item in pasteboardItems {
                item.types.filter { ![NSPasteboard.PasteboardType.rtf, NSPasteboard.PasteboardType(rawValue: "public.utf16-external-plain-text")].contains($0) }.forEach { type in
                    print(type.rawValue + " " + (item.string(forType: type) ?! String(describing: item.propertyList(forType: type) ?? item.data(forType: type) ?? "<EMPTY DATA>")))
                }
            }
        #endif
    }
}

typealias AppDelegateParent = LowtechProAppDelegate

enum OptimisationSource: Codable, Equatable, Hashable {
    case clipboard
    case service
    case photos
    case openWith
    case fileWatcher
    case shortcuts
    case cli
    case dropZone
    case finder
    case dir(String)

    var string: String {
        switch self {
        case .clipboard: "clipboard"
        case .service: "service"
        case .photos: "photos"
        case .openWith: "openWith"
        case .fileWatcher: "fileWatcher"
        case .shortcuts: "shortcuts"
        case .cli: "cli"
        case .dropZone: "dropZone"
        case .finder: "finder"
        case let .dir(dir): dir
        }
    }
}

extension String {
    var optSource: OptimisationSource? {
        switch self {
        case "clipboard": .clipboard
        case "service": .service
        case "photos": .photos
        case "shortcuts": .shortcuts
        case "cli": .cli
        case "finder": .finder
        case "openWith", "open-with", "open with": .openWith
        case "fileWatcher", "file-watcher", "file watcher": .fileWatcher
        case "dropZone", "drop-zone", "drop zone": .dropZone
        default: .dir(self)
        }
    }
}

/// Determine which app placed the current clipboard content, for the `copiedBy` pipeline filter.
/// Prefers the explicit `org.nspasteboard.source` bundle id, then the last-focused / frontmost app.
@MainActor func clipboardSourceApp(item: NSPasteboardItem?) -> (bundleID: String?, name: String?) {
    if let bundleID = item?.string(forType: NSPasteboard.PasteboardType("org.nspasteboard.source")), !bundleID.isEmpty {
        let name = NSWorkspace.shared.urlForApplication(withBundleIdentifier: bundleID).flatMap { Bundle(url: $0)?.name }
        return (bundleID, name)
    }
    if let id = LastFocusedAppTracker.shared.bundleId {
        return (id, LastFocusedAppTracker.shared.name)
    }
    let app = NSWorkspace.shared.frontmostApplication
    return (app?.bundleIdentifier, app?.localizedName)
}

class AppDelegate: AppDelegateParent {
    @MainActor
    override public func willShowPaddle(_: PADUIType, product _: PADProduct) -> PADDisplayConfiguration? {
        PADDisplayConfiguration(.window, hideNavigationButtons: false, parentWindow: nil)
    }

    var proDebugCancellables = Set<AnyCancellable>()

    var videoWatcher: FileOptimisationWatcher?
    var imageWatcher: FileOptimisationWatcher?
    var pdfWatcher: FileOptimisationWatcher?
    var audioWatcher: FileOptimisationWatcher?

    @MainActor var swipeEnded = true

    @Setting(.floatingResultsCorner) var floatingResultsCorner
    lazy var draggingSet: PassthroughSubject<Bool, Never> = debouncer(in: &observers, every: .milliseconds(200)) { dragging in
        mainActor {
            DM.dragging = dragging
            if !dragging {
                DM.dropped = true
            } else {
                showFloatingThumbnails(force: true)
            }
        }
    }

    var lastDragChangeCount = NSPasteboard(name: .drag).changeCount

    @MainActor lazy var dragMonitor = GlobalEventMonitor(mask: [.leftMouseDragged]) { event in
        guard self.finishedOnboarding, NSEvent.pressedMouseButtons > 0, proactive || DM.optimisationCount <= 5 else {
            return
        }

        let drag = NSPasteboard(name: .drag)
//        drag.debug()
        guard self.lastDragChangeCount != drag.changeCount else {
            return
        }
        DM.dropped = false
        self.lastDragChangeCount = drag.changeCount

        guard let items = drag.pasteboardItems, !items.contains(where: { $0.types.set.hasElements(from: [.promise, .promisedFileName, .promisedFileURL, .promisedSuggestedFileName, .promisedMetadata]) }) else {
            DM.itemsToOptimise = []
            self.draggingSet.send(true)
            return
        }

        dropZoneKeyGlobalMonitor.start()
        dropZoneKeyLocalMonitor.start()
        presetZonesKeyGlobalMonitor.start()
        presetZonesKeyLocalMonitor.start()

        let toOptimise: [ClipboardType] = items.compactMap { item -> ClipboardType? in
            let types = item.types
            guard !types.contains(.init("com.apple.finalcutpro.xml")) else {
                return nil
            }

            if types.contains(.fileURL), let url = item.string(forType: .fileURL)?.url,
               let path = url.existingFilePath, path.isImage || path.isVideo || path.isAudio || path.isPDF
            {
                return .file(path)
            }

            if let str = item.string(forType: .string), let path = str.existingFilePath, path.isImage || path.isVideo || path.isAudio || path.isPDF {
                return .file(path)
            }

            if types.contains(.URL), let url = item.string(forType: .URL)?.url ?? item.string(forType: .string)?.url, url.isImage || url.isVideo || url.isPDF {
                return .url(url)
            }

            if types.set.hasElements(from: IMAGE_VIDEO_PASTEBOARD_TYPES) || types.contains(.pdf) {
                return .file(FilePath.tmp)
            }

            if let str = item.string(forType: .string), let url = str.url, url.isImage || url.isVideo || url.isPDF {
                return .url(url)
            }

            return nil
        }

        guard toOptimise.isNotEmpty else {
            DM.itemsToOptimise = []
            return
        }

        DM.itemsToOptimise = toOptimise
        self.draggingSet.send(true)
    }

    @MainActor lazy var mouseUpMonitor = GlobalEventMonitor(mask: [.leftMouseUp]) { event in
        self.draggingSet.send(false)
        if !DM.dragHovering, DM.itemsToOptimise.isNotEmpty {
            DM.dragging = false
            DM.itemsToOptimise = []
        }
    }

    @Setting(.optimiseVideoClipboard) var optimiseVideoClipboard

    var machPortThread: Thread?
    var machPortStopThread: Thread?

    var finishedOnboarding = Defaults[.finishedOnboarding] || Defaults[.launchCount] > 5

    lazy var onboardingWindowController: NSWindowController? = {
        let window = NSWindow(contentViewController: NSHostingController(rootView: OnboardingView()))
        window.title = "Onboarding"
        window.titleVisibility = .hidden
        window.titlebarAppearsTransparent = true
        window.styleMask = [.closable, .resizable, .titled]
        window.center()
        let wc = NSWindowController(window: window)
        window.windowController = wc

        return wc
    }()

    var sentryCrashExceptionApplicationType: AnyClass?

    var fileCleaner: Timer?

    override func applicationDidFinishLaunching(_ notification: Notification) {
        sentryCrashExceptionApplicationType = SentryCrashExceptionApplication.self
        if !SWIFTUI_PREVIEW {
            handleCLIInstall()

            NSApplication.shared.windows.first { $0.title == "Settings" }?.close()
            unarchiveBinaries()
            print(NSFilePromiseReceiver.swizzleReceivePromisedFiles)
            NSView.swizzleDragFormation()
            swizzleDraggableToRealPath()
            shouldRestartOnCrash = true

            NSRunningApplication.runningApplications(withBundleIdentifier: Bundle.main.bundleIdentifier!)
                .filter { $0.processIdentifier != ProcessInfo.processInfo.processIdentifier }
                .forEach {
                    $0.forceTerminate()
                }
            let _ = shell("/usr/bin/pkill", args: ["-fl", "Clop/bin/(arm64|x86)/.+"], wait: false)
            signal(SIGTERM) { _ in
                for opt in OM.optimisers + OM.removedOptimisers {
                    opt.stop(animateRemoval: false)
                }
                exit(0)
            }
            signal(SIGKILL) { _ in
                for opt in OM.optimisers + OM.removedOptimisers {
                    opt.stop(animateRemoval: false)
                }
                exit(0)
            }

            syncSettings()
            _ = LastFocusedAppTracker.shared
            Defaults[.cliInstalled] = fm.fileExists(atPath: CLOP_CLI_BIN_LINK)
            Migrations.run()
            createFileCleaner()
        }

        paddleVendorID = "122873"
        paddleAPIKey = "e1e517a68c1ed1bea2ac968a593ac147"
        paddleProductID = "841006"
        trialDays = 14
        trialText = "This is a trial for the Pro features. After the trial, the app will automatically revert to the free version."
        price = 15
        productName = "Clop Pro"
        vendorName = "THE LOW TECH GUYS SRL"
        hasFreeFeatures = true

        if !SWIFTUI_PREVIEW {
            LowtechSentry.sentryDSN = "https://7dad9331a2e1753c3c0c6bc93fb0d523@o84592.ingest.sentry.io/4505673793077248"
            LowtechSentry.configureSentry(restartOnHang: false, getUser: LowtechSentry.getSentryUser)
            configureAppHangDetection { _, _ in
                activeCLIRequests.load(ordering: .relaxed) > 0 ? .suppressRestart : .useDefault
            }

            KM.primaryKeyModifiers = Defaults[.keyComboModifiers]
            KM.primaryKeys = Defaults[.enabledKeys] + Defaults[.quickResizeKeys]
            KM.onPrimaryHotkey = { key in
                self.handleHotkey(key)
                let _ = invalidReq2(PRODUCTS, nil)
            }

            KM.secondaryKeyModifiers = [.lcmd]
            KM.onSecondaryHotkey = { key in
                self.handleCommandHotkey(key)
                let _ = invalidReq3(PRODUCTS, nil)
            }
        }
        super.applicationDidFinishLaunching(_: notification)
        UM.updater = updateController.updater
        PM.pro = pro
        if !SWIFTUI_PREVIEW {
            clopDebugLog("applicationDidFinishLaunching: about to checkProLicense (productActivated=\(pro.productActivated), onTrial=\(pro.onTrial))")
            pro.checkProLicense()
        }

        let p = pro
        p.$productActivated.sink { newValue in
            clopDebugLog("proactive observer: productActivated changed to \(newValue) (onTrial=\(p.onTrial), proactive will be \(newValue || p.onTrial))")
        }.store(in: &proDebugCancellables)
        p.$onTrial.sink { newValue in
            clopDebugLog("proactive observer: onTrial changed to \(newValue) (productActivated=\(p.productActivated), proactive will be \(p.productActivated || newValue))")
        }.store(in: &proDebugCancellables)

        Defaults[.videoDirs] = Defaults[.videoDirs].filter { fm.fileExists(atPath: $0) }
        migrateShortcutsToPipelines()
        migrateToUnifiedCompression()

        BetaLicenseChecker.start()

        guard !SWIFTUI_PREVIEW else { return }

        #if DEBUG
            settingsViewManager.tab = .automation
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
                WM.open("settings")
                focus()
            }
        #endif

        floatingResultsWindow.animateOnResize = false
        pub(.allowClopToAppearInScreenshots)
            .sink {
                floatingResultsWindow.sharingType = $0.newValue ? .readOnly : .none
            }
            .store(in: &observers)
        pub(.workdir)
            .sink {
                FilePath.workdir = FilePath.dir($0.newValue, permissions: 0o777)
            }
            .store(in: &observers)
        pub(.floatingResultsCorner)
            .sink {
                floatingResultsWindow.screenCorner = $0.newValue
                floatingResultsWindow.moveToScreen(.withMouse, corner: $0.newValue)
            }
            .store(in: &observers)
        pub(.keyComboModifiers)
            .sink {
                KM.primaryKeyModifiers = $0.newValue
                KM.reinitHotkeys()
            }
            .store(in: &observers)
        pub(.quickResizeKeys)
            .sink {
                KM.primaryKeys = Defaults[.enabledKeys] + $0.newValue
                KM.reinitHotkeys()
            }
            .store(in: &observers)
        pub(.enabledKeys)
            .sink {
                KM.primaryKeys = $0.newValue + Defaults[.quickResizeKeys]
                KM.reinitHotkeys()
            }
            .store(in: &observers)
        pub(.enableFloatingResults)
            .sink {
                if $0.newValue {
                    showFloatingThumbnails(force: true)
                } else {
                    floatingResultsWindow.close()
                }
            }
            .store(in: &observers)

        if finishedOnboarding {
            initOptimisers()
        } else {
            onboardFileOptimisation()
        }
        trackScrollWheel()

        if Defaults[.enableDragAndDrop] {
            dragMonitor.start()
            mouseUpMonitor.start()
        }
        pub(.enableDragAndDrop)
            .sink { enabled in
                if enabled.newValue {
                    self.dragMonitor.start()
                    self.mouseUpMonitor.start()
                } else {
                    self.dragMonitor.stop()
                    self.mouseUpMonitor.stop()
                }
            }
            .store(in: &observers)
        pub(.enableClipboardOptimiser)
            .sink { enabled in
                if enabled.newValue {
                    self.initClipboardOptimiser()
                } else {
                    clipboardWatcher?.invalidate()
                }
            }
            .store(in: &observers)
        pub(.pauseAutomaticOptimisations)
            .sink { paused in
                if paused.newValue {
                    clipboardWatcher?.invalidate()
                } else {
                    self.initClipboardOptimiser()
                }
            }
            .store(in: &observers)
        initMachPortListener()

        let _ = invalidReq(PRODUCTS, nil)
        setupServiceProvider()
        startShortcutWatcher()
        DROPSHARE.fetchAppURL()
        DROPOVER.fetchAppURL()
        YOINK.fetchAppURL()
        DOCKSIDE.fetchAppURL()
        ATOLL.fetchAppURL()

        // listen for NSWindow.willCloseNotification to release the window
        NotificationCenter.default.addObserver(self, selector: #selector(windowWillClose), name: NSWindow.willCloseNotification, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(windowDidBecomeMainNotification), name: NSWindow.didBecomeMainNotification, object: nil)
    }

    override func applicationDidBecomeActive(_ notification: Notification) {
        didBecomeActiveAtLeastOnce = true
    }

    @MainActor
    static func handleStopOptimisationRequest(_ req: StopOptimisationRequest) {
        log.debug("Stopping optimisation request: \(req.jsonString)")

        for id in req.ids {
            guard let opt = opt(id) else {
                continue
            }

            opt.stop(remove: req.remove)
            opt.uiStop()
        }
    }

    static func handleOptimisationRequest(_ req: OptimisationRequest) -> Data? {
        log.debug("Handling optimisation request: \(req.jsonString)")

        activeCLIRequests.wrappingIncrement(ordering: .relaxed)
        defer { activeCLIRequests.wrappingDecrement(ordering: .relaxed) }

        let sem = DispatchSemaphore(value: 0)
        var resp: [OptimisationResponse] = []
        tryAsync {
            resp = try await processOptimisationRequest(req)
            sem.signal()
        }
        sem.wait()

        return resp.jsonData
    }

    func application(_ application: NSApplication, open urls: [URL]) {
        Task.init {
            await handleURLs(application, urls)
        }
    }

    func application(_ sender: NSApplication, openFiles filenames: [String]) {
        Task.init {
            await handleURLs(sender, filenames.compactMap(\.url))
        }
    }

    func handleURLs(_ application: NSApplication, _ urls: [URL]) async {
        do {
            try await withThrowingTaskGroup(of: Void.self, returning: Void.self) { group in
                for item in urls.map(ClipboardType.fromURL(_:)) {
                    let source: OptimisationSource = item.path.string.contains("com.apple.Photos") ? .photos : .openWith
                    let added = group.addTaskUnlessCancelled {
                        try await optimiseItem(
                            item,
                            id: item.id,
                            adaptiveOptimisation: false,
                            optimisationCount: &manualOptimisationCount,
                            copyToClipboard: false,
                            source: source,
                            removeAudio: false,
                            optimisedFileBehaviour: source == .photos ? .inPlace : nil
                        )
                    }
                    guard added else { break }
                    try await group.next()
                }
            }
        } catch {
            log.error("Error optimising files from 'Open with': \(error.localizedDescription)")
            application.reply(toOpenOrPrint: .failure)
        }
        application.reply(toOpenOrPrint: .success)
    }

    func setupServiceProvider() {
        NSApp.registerServicesMenuSendTypes([.png, .pdf, .fileURL, .fileContents], returnTypes: [.png, .pdf, .fileURL, .fileContents])
        NSApplication.shared.servicesProvider = ContextualMenuServiceProvider()
        NSUpdateDynamicServices()
    }

    @MainActor
    func handleCommandHotkey(_ key: SauceKey) {
        guard finishedOnboarding, let opt = OM.hovered else {
            return
        }

        switch key {
        case .comma:
            WM.open("settings")
            focus()
        case .minus where opt.downscaleFactor > 0.1:
            opt.stepDownscale()
        case .x where opt.changePlaybackSpeedFactor < 10 && opt.canChangePlaybackSpeed():
            opt.changePlaybackSpeed()
        case .delete:
            hoveredOptimiserID = nil
            opt.stop(animateRemoval: true)
        case .space:
            opt.quicklook()
        case .z where !opt.isOriginal:
            opt.restoreOriginal()
        case .r where !opt.running:
            opt.editingFilename = true
        case .d where !opt.type.isAudio && opt.url != nil && opt.comparisonOriginalURL != nil:
            opt.compare()
        case .c:
            opt.copyToClipboard()
            opt.overlayMessage = "Copied"
        case .s:
            opt.save()
        case .f:
            opt.showInFinder()
        case .u:
            DROPSHARE.open(optimiser: opt)
        case .w:
            if let session = WDM.session(forOptimiser: opt) {
                session.copyLink()
                opt.overlayMessage = "Copied link"
            } else {
                warpDropSend(optimiser: opt)
            }
        case .o:
            guard let url = opt.url ?? opt.originalURL else { return }
            NSWorkspace.shared.open(url)
        case .a where !opt.aggressive:
            if opt.downscaleFactor < 1 {
                opt.downscale(toFactor: opt.downscaleFactor, aggressiveOptimisation: true)
            } else {
                opt.optimise(allowLarger: false, aggressiveOptimisation: true, fromOriginal: true)
            }
        default:
            return
        }
    }

    @MainActor
    func handleHotkey(_ key: SauceKey) {
        guard finishedOnboarding else { return }

        switch key {
        case .escape:
            OM.clearVisibleOptimisers(stop: true)
        case .minus:
            if let opt = OM.current {
                guard opt.downscaleFactor > 0.1 else { return }
                opt.stepDownscale()
            } else {
                guard scalingFactor > 0.1 else { return }
                scalingFactor = max(scalingFactor > 0.5 ? scalingFactor - 0.25 : scalingFactor - 0.1, 0.1)
                Task.init { try? await optimiseLastClipboardItem(downscaleTo: scalingFactor) }
            }
        case .x:
            if let opt = OM.current, opt.canChangePlaybackSpeed() {
                guard opt.changePlaybackSpeedFactor < 10 else { return }
                opt.changePlaybackSpeed()
            } else {
                Task.init { try? await optimiseLastClipboardItem(changePlaybackSpeedBy: 1.25) }
            }
        case .r:
            if let opt = OM.current, !opt.running {
                opt.editingFilename = true
            }
        case .delete:
            if let opt = OM.optimisers.filter({ !$0.inRemoval && !$0.hidden }).max(by: \.startedAt) {
                hoveredOptimiserID = nil
                opt.stop(animateRemoval: true)
            }
        case .equal:
            if let opt = OM.removedOptimisers.popLast() {
                opt.bringBack()
            }
        case .space:
            if let opt = OM.current, !opt.inRemoval {
                opt.quicklook()
            } else {
                Task.init { try? await quickLookLastClipboardItem() }
            }
        case .z:
            if let opt = OM.current, !opt.inRemoval, !opt.isOriginal {
                opt.restoreOriginal()
            }
        case .p:
            if Defaults[.pauseAutomaticOptimisations] {
                Defaults[.pauseAutomaticOptimisations] = false
                pauseForNextClipboardEvent = false
                showNotice("**Running** • Paused • Stopped\nClop is listening for clipboard and file events")
            } else if pauseForNextClipboardEvent {
                Defaults[.pauseAutomaticOptimisations] = true
                showNotice("Running • Paused • **Stopped**\nAll automatic optimisations are stopped")
            } else {
                pauseForNextClipboardEvent = true
                showNotice("Running • **Paused** • Stopped\nNext clipboard event will be ignored")
            }
        case .c:
            Task.init { try? await optimiseLastClipboardItem() }
        case .a:
            if let opt = OM.current, !opt.inRemoval {
                guard !opt.aggressive else { return }
                if opt.downscaleFactor < 1 {
                    opt.downscale(toFactor: opt.downscaleFactor, aggressiveOptimisation: true)
                } else {
                    opt.optimise(allowLarger: false, aggressiveOptimisation: true, fromOriginal: true)
                }
            } else {
                Task.init { try? await optimiseLastClipboardItem(aggressiveOptimisation: true) }
            }
        case SauceKey.NUMBER_KEYS.suffix(from: 1).arr:
            guard let number = key.QWERTYCharacter.d else { break }

            if let opt = OM.current, !opt.inRemoval {
                opt.downscale(toFactor: number / 10.0)
            } else {
                Task.init { try? await optimiseLastClipboardItem(downscaleTo: number / 10.0) }
            }
        default:
            break
        }
    }

    func syncSettings() {
        if Defaults[.syncSettingsCloud] {
            Zephyr.observe(keys: SETTINGS_TO_SYNC)
        }
        pub(.syncSettingsCloud)
            .sink { change in
                if change.newValue {
                    Zephyr.observe(keys: SETTINGS_TO_SYNC)
                } else {
                    Zephyr.stopObserving(keys: SETTINGS_TO_SYNC)
                }
            }.store(in: &observers)
    }
    func initMachPortListener() {
        machPortThread = Thread {
            OPTIMISATION_PORT.listen { data in
                guard let data else {
                    return nil
                }

                var result: Data? = nil
                if let req = OptimisationRequest.from(data) {
                    result = Self.handleOptimisationRequest(req)
                }

                guard let result else {
                    return nil
                }
                return Unmanaged.passRetained(result as CFData)
            }
            RunLoop.current.run()
        }
        machPortStopThread = Thread {
            OPTIMISATION_STOP_PORT.listen { data in
                guard let data, let req = StopOptimisationRequest.from(data) else {
                    return nil
                }

                mainActor { Self.handleStopOptimisationRequest(req) }
                return nil
            }
            RunLoop.current.run()
        }

        machPortThread?.start()
        machPortStopThread?.start()
    }

    func applicationWillFinishLaunching(_ notification: Notification) {
        if !SWIFTUI_PREVIEW {
            migrateSettings()
            resetDefaultPlayer()
        }
    }

    func createFileCleaner() {
        fileCleaner = Timer.scheduledTimer(withTimeInterval: 600, repeats: true) { _ in
            let interval = Defaults[.workdirCleanupInterval]
            guard interval != .never else {
                return
            }

            for dir in [FilePath.clopBackups, .videos, .images, .pdfs, .conversions, .downloads, .forResize, .forFilters, .finderQuickAction, .processLogs] {
                let enumerator = fm.enumerator(at: dir.url, includingPropertiesForKeys: [.attributeModificationDateKey, .isDirectoryKey], options: [.skipsHiddenFiles, .skipsPackageDescendants])
                guard let iterator = enumerator else {
                    return
                }

                let now = Date()
                while case let url as URL = iterator.nextObject() {
                    if let isdir = try? url.resourceValues(forKeys: [.isDirectoryKey]).isDirectory, isdir {
                        continue
                    }
                    guard let date = try? url.resourceValues(forKeys: [.attributeModificationDateKey]).attributeModificationDate else {
                        continue
                    }

                    if now.timeIntervalSince(date) > interval.rawValue {
                        log.debug("Deleting \(url.path) because it's older than \(interval.title) (last modified \(date))")
                        try? fm.removeItem(at: url)
                    }
                }
            }
        }
        fileCleaner?.tolerance = 300
        fileCleaner?.fire()
    }

    @MainActor
    func onboardFileOptimisation() {
        print(OnboardingFloatingPreview.om)
        NSApp.setActivationPolicy(.regular)
        onboardingWindowController?.showWindow(self)
        focus()
    }

    @objc func windowWillClose(_ notification: Notification) {
        guard let window = notification.object as? NSWindow else { return }

        if window.title == "Settings" || window.title == "Comparison" {
            mainActor {
                settingsViewManager.windowOpen = false
                NSApp.setActivationPolicy(.accessory)
            }
        }

        if window.title == "Onboarding" {
            mainActor {
                self.finishedOnboarding = true
                Defaults[.finishedOnboarding] = true
                self.initOptimisers()
                NSApp.setActivationPolicy(.accessory)
                self.onboardingWindowController?.window = nil
                self.onboardingWindowController = nil
            }
        }
    }

    @objc func windowDidBecomeMainNotification(_ notification: Notification) {
        guard let window = notification.object as? NSWindow else { return }

        if let paddleController = window.windowController as? PADActivateWindowController,
           let email = paddleController.emailTxt, let licenseCode = paddleController.licenseTxt
        {
            email.isBordered = true
            licenseCode.isBordered = true

            email.drawsBackground = true
            licenseCode.drawsBackground = true

            email.backgroundColor = .black.withAlphaComponent(0.05)
            licenseCode.backgroundColor = .black.withAlphaComponent(0.05)
        }

        if window.title.contains("Updat") {
            focus()
            return
        }

        if window.title == "Comparison" {
            NSApp.setActivationPolicy(.regular)
            return
        }

        if window.title == "Settings" {
            mainActor {
                print(FloatingPreview.om, CompactPreview.om)
                settingsViewManager.windowOpen = true
                NSApp.setActivationPolicy(.regular)

                log.debug("Starting settings tab key monitor")
                tabKeyMonitor.start()
            }
        }
    }

    func trackScrollWheel() {
        NSApp.publisher(for: \.currentEvent)
            .filter { event in event?.type == .scrollWheel }
            .throttle(
                for: .milliseconds(20),
                scheduler: DispatchQueue.main,
                latest: true
            )
            .sink { event in
                guard let event else { return }

                mainActor {
                    if self.swipeEnded, !OM.compactResults, self.floatingResultsCorner.isTrailing ? event.scrollingDeltaX > 3 : event.scrollingDeltaX < -3,
                       let hov = hoveredOptimiserID, let optimiser = OM.optimisers.first(where: { $0.id == hov })
                    {
                        hoveredOptimiserID = nil
                        optimiser.stop(remove: true, animateRemoval: true)
                        self.swipeEnded = false
                    }
                    if event.scrollingDeltaX == 0 {
                        self.swipeEnded = true
                    }
                }
            }.store(in: &observers)

        NSEvent.addLocalMonitorForEvents(matching: .keyDown) { event in
            guard let hov = hoveredOptimiserID,
                  let optimiser = OM.optimisers.first(where: { $0.id == hov }),
                  event.modifierFlags.contains(.command)
            else { return event }

            switch event.charactersIgnoringModifiers {
            case "e":
                guard let shelfApp = runningShelfApp() else { return event }
                shelfApp.open(optimiser: optimiser)
                return nil
            case "f":
                optimiser.showInFinder()
                return nil
            default:
                return event
            }
        }
    }

    func applicationShouldHandleReopen(_: NSApplication, hasVisibleWindows _: Bool) -> Bool {
        if !Defaults[.showMenubarIcon] {
            WM.open("settings")
            focus()
        }

        return true
    }
    func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
        false
    }

    @MainActor func initOptimisers() {
        guard finishedOnboarding else { return }
        let debounceMS = Defaults[.launchCount] == 1 ? 800 : 100

        videoWatcher = FileOptimisationWatcher(
            pathsKey: .videoDirs,
            enabledKey: .enableAutomaticVideoOptimisations,
            maxFilesToHandleKey: .maxVideoFileCount,
            fileType: .video,
            shouldHandle: shouldHandleVideo(event:),
            cancel: cancelVideoOptimisation(path:)
        ) { path in
            guard OM.visibleOptimisers.first(where: { $0.running && $0.id == path.string }) == nil,
                  !OM.optimisers.contains(where: { $0.url?.path == path.string })
            else {
                return
            }
            Task.init {
                // Skip videos below the minimum resolution (metadata is only fetched when enabled).
                let minRes = Defaults[.minVideoResolution]
                if minRes > 0, let video = try? await Video.byFetchingMetadata(path: path, thumb: false),
                   let res = video.size, res.width < CGFloat(minRes) || res.height < CGFloat(minRes) {
                    return
                }
                let matchedDir = Defaults[.videoDirs].filter { path.string.starts(with: $0) }.max(by: \.count)
                let source = matchedDir?.optSource
                let hide = matchedDir.map { Defaults[.dirsHideFloatingResult].contains($0) } ?? false
                let type: ItemType = .video(UTType.from(filePath: path) ?? .mpeg4Movie)
                let pipelines = source.map { pipelinesFor(type: type, source: $0) } ?? []
                let allSkip = !pipelines.isEmpty && pipelines.allSatisfy(\.skipOptimisation)

                var resultPath = path
                if allSkip {
                    let optimiser = OM.optimiser(id: path.string, type: type, operation: "Running pipeline", hidden: true, source: source)
                    optimiser.url = path.url
                    if let source {
                        await runPipelinesAfterOptimisation(file: resultPath, type: type, source: source, optimiser: optimiser)
                    }
                } else {
                    let video = Video(path: path)
                    if let result = try? await runVideoPipeline(video, actions: [.optimise], debounceMS: debounceMS, hideFloatingResult: hide, source: source) {
                        resultPath = result.path
                    }
                    if let source, let optimiser = opt(path.string) {
                        await runPipelinesAfterOptimisation(file: resultPath, type: type, source: source, optimiser: optimiser)
                    }
                }
            }
        }
        imageWatcher = FileOptimisationWatcher(
            pathsKey: .imageDirs,
            enabledKey: .enableAutomaticImageOptimisations,
            maxFilesToHandleKey: .maxImageFileCount,
            fileType: .image,
            shouldHandle: shouldHandleImage(event:),
            cancel: cancelImageOptimisation(path:)
        ) { path in
            guard OM.visibleOptimisers.first(where: { $0.running && $0.id == path.string }) == nil,
                  !OM.optimisers.contains(where: { $0.url?.path == path.string })
            else {
                return
            }
            Task.init {
                let matchedDir = Defaults[.imageDirs].filter { path.string.starts(with: $0) }.max(by: \.count)
                let source = matchedDir?.optSource
                let hide = matchedDir.map { Defaults[.dirsHideFloatingResult].contains($0) } ?? false
                guard let img = Image(path: path, retinaDownscaled: false) else { return }
                let type: ItemType = .image(img.type)
                let pipelines = source.map { pipelinesFor(type: type, source: $0) } ?? []
                let allSkip = !pipelines.isEmpty && pipelines.allSatisfy(\.skipOptimisation)

                var resultPath = path
                if allSkip {
                    let optimiser = OM.optimiser(id: path.string, type: type, operation: "Running pipeline", hidden: true, source: source)
                    optimiser.url = path.url
                    if let source {
                        await runPipelinesAfterOptimisation(file: resultPath, type: type, source: source, optimiser: optimiser)
                    }
                } else {
                    if let result = try? await runImagePipeline(img, actions: [.optimise], debounceMS: debounceMS, hideFloatingResult: hide, source: source) {
                        resultPath = result.path
                    }
                    if let source, let optimiser = opt(path.string) {
                        await runPipelinesAfterOptimisation(file: resultPath, type: type, source: source, optimiser: optimiser)
                    }
                }
            }
        }
        pdfWatcher = FileOptimisationWatcher(
            pathsKey: .pdfDirs,
            enabledKey: .enableAutomaticPDFOptimisations,
            maxFilesToHandleKey: .maxPDFFileCount,
            fileType: .pdf,
            shouldHandle: shouldHandlePDF(event:),
            cancel: cancelPDFOptimisation(path:)
        ) { path in
            guard OM.visibleOptimisers.first(where: { $0.running && $0.id == path.string }) == nil,
                  !OM.optimisers.contains(where: { $0.url?.path == path.string })
            else {
                return
            }
            Task.init {
                let matchedDir = Defaults[.pdfDirs].filter { path.string.starts(with: $0) }.max(by: \.count)
                let source = matchedDir?.optSource
                let hide = matchedDir.map { Defaults[.dirsHideFloatingResult].contains($0) } ?? false
                let type: ItemType = .pdf
                let pipelines = source.map { pipelinesFor(type: type, source: $0) } ?? []
                let allSkip = !pipelines.isEmpty && pipelines.allSatisfy(\.skipOptimisation)

                var resultPath = path
                if allSkip {
                    let optimiser = OM.optimiser(id: path.string, type: type, operation: "Running pipeline", hidden: true, source: source)
                    optimiser.url = path.url
                    if let source {
                        await runPipelinesAfterOptimisation(file: resultPath, type: type, source: source, optimiser: optimiser)
                    }
                } else {
                    if let result = try? await runPDFPipeline(PDF(path), actions: [.optimise], debounceMS: debounceMS, hideFloatingResult: hide, source: source) {
                        resultPath = result.path
                    }
                    if let source, let optimiser = opt(path.string) {
                        await runPipelinesAfterOptimisation(file: resultPath, type: type, source: source, optimiser: optimiser)
                    }
                }
            }
        }
        audioWatcher = FileOptimisationWatcher(
            pathsKey: .audioDirs,
            enabledKey: .enableAutomaticAudioOptimisations,
            maxFilesToHandleKey: .maxAudioFileCount,
            fileType: .audio,
            shouldHandle: shouldHandleAudio(event:),
            cancel: cancelAudioOptimisation(path:)
        ) { path in
            guard OM.visibleOptimisers.first(where: { $0.running && $0.id == path.string }) == nil,
                  !OM.optimisers.contains(where: { $0.url?.path == path.string })
            else {
                return
            }
            Task.init {
                let matchedDir = Defaults[.audioDirs].filter { path.string.starts(with: $0) }.max(by: \.count)
                let source = matchedDir?.optSource
                let hide = matchedDir.map { Defaults[.dirsHideFloatingResult].contains($0) } ?? false
                let type: ItemType = .audio(UTType.from(filePath: path) ?? .mp3)
                let pipelines = source.map { pipelinesFor(type: type, source: $0) } ?? []
                let allSkip = !pipelines.isEmpty && pipelines.allSatisfy(\.skipOptimisation)

                var resultPath = path
                if allSkip {
                    let optimiser = OM.optimiser(id: path.string, type: type, operation: "Running pipeline", hidden: true, source: source)
                    optimiser.url = path.url
                    if let source {
                        await runPipelinesAfterOptimisation(file: resultPath, type: type, source: source, optimiser: optimiser)
                    }
                } else {
                    if let result = try? await runAudioPipeline(Audio(path: path), actions: [.optimise], debounceMS: debounceMS, hideFloatingResult: hide, source: source) {
                        resultPath = result.path
                    }
                    if let source, let optimiser = opt(path.string) {
                        await runPipelinesAfterOptimisation(file: resultPath, type: type, source: source, optimiser: optimiser)
                    }
                }
            }
        }

        if Defaults[.enableClipboardOptimiser], !Defaults[.pauseAutomaticOptimisations] {
            initClipboardOptimiser()
        }

        let _ = invalidReq(PRODUCTS, nil)
    }

    @MainActor func initClipboardOptimiser() {
        guard finishedOnboarding else { return }

        clipboardWatcher?.invalidate()
        clipboardWatcher = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { _ in
            let newChangeCount = NSPasteboard.general.changeCount
            guard newChangeCount != pbChangeCount else {
                return
            }
            pbChangeCount = newChangeCount
            guard !pauseForNextClipboardEvent else {
                pauseForNextClipboardEvent = false
                return
            }
            guard let item = NSPasteboard.general.pasteboardItems?.first, item.string(forType: .optimisationStatus) == nil, !TRANSIENT_TYPES.hasElements(from: Set(item.types)) else {
                return
            }

            let ignoredApps = Defaults[.clipboardIgnoredAppBundleIds]
            if !ignoredApps.isEmpty,
               let frontmostBundleID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier,
               ignoredApps.contains(frontmostBundleID)
            {
                return
            }

            mainActor {
                guard !BM.decompressingBinaries else {
                    return
                }

                scalingFactor = 1
                // Capture the app that placed this clipboard content for the `copiedBy` pipeline filter.
                OM.lastClipboardSourceApp = clipboardSourceApp(item: item)

                if self.optimiseVideoClipboard, let path = item.existingFilePath, path.isVideo {
                    let ignore = Defaults[.videoFormatsToSkip]
                    if !ignore.isEmpty, let itemType = ItemType.from(filePath: path).utType, ignore.contains(itemType) {
                        return
                    }
                    let alreadyOptimised = path.hasOptimisationStatusXattr()
                    if alreadyOptimised {
                        let type: ItemType = .video(UTType.from(filePath: path) ?? .mpeg4Movie)
                        let pipelines = pipelinesFor(type: type, source: .clipboard)
                        if !pipelines.isEmpty {
                            Task.init {
                                let optimiser = OM.optimiser(id: path.string, type: type, operation: "Running pipeline", hidden: true, source: .clipboard)
                                optimiser.url = path.url
                                await runPipelinesAfterOptimisation(file: path, type: type, source: .clipboard, optimiser: optimiser)
                            }
                        }
                    } else {
                        Task.init {
                            let type: ItemType = .video(UTType.from(filePath: path) ?? .mpeg4Movie)
                            var resultPath = path
                            if let result = try? await runVideoPipeline(Video(path: path), actions: [.optimise], source: .clipboard) {
                                resultPath = result.path
                            }
                            if let optimiser = opt(path.string) {
                                await runPipelinesAfterOptimisation(file: resultPath, type: type, source: .clipboard, optimiser: optimiser)
                            }
                        }
                    }
                    return
                }
                if Defaults[.optimisePDFClipboard], let path = item.existingFilePath, path.isPDF {
                    let alreadyOptimised = path.hasOptimisationStatusXattr()
                    if alreadyOptimised {
                        let type: ItemType = .pdf
                        let pipelines = pipelinesFor(type: type, source: .clipboard)
                        if !pipelines.isEmpty {
                            Task.init {
                                let optimiser = OM.optimiser(id: path.string, type: type, operation: "Running pipeline", hidden: true, source: .clipboard)
                                optimiser.url = path.url
                                await runPipelinesAfterOptimisation(file: path, type: type, source: .clipboard, optimiser: optimiser)
                            }
                        }
                    } else {
                        Task.init {
                            var resultPath = path
                            if let result = try? await runPDFPipeline(PDF(path), actions: [.optimise], source: .clipboard) {
                                resultPath = result.path
                            }
                            if let optimiser = opt(path.string) {
                                await runPipelinesAfterOptimisation(file: resultPath, type: .pdf, source: .clipboard, optimiser: optimiser)
                            }
                        }
                    }
                    return
                }
                if item.existingFilePath?.isPDF ?? false {
                    return
                }
                if Defaults[.optimiseAudioClipboard], let path = item.existingFilePath, path.isAudio {
                    let ignore = Defaults[.audioFormatsToSkip]
                    if !ignore.isEmpty, let itemType = ItemType.from(filePath: path).utType, ignore.contains(itemType) {
                        return
                    }
                    let alreadyOptimised = path.hasOptimisationStatusXattr()
                    if alreadyOptimised {
                        let type: ItemType = .audio(UTType.from(filePath: path) ?? .mp3)
                        let pipelines = pipelinesFor(type: type, source: .clipboard)
                        if !pipelines.isEmpty {
                            Task.init {
                                let optimiser = OM.optimiser(id: path.string, type: type, operation: "Running pipeline", hidden: true, source: .clipboard)
                                optimiser.url = path.url
                                await runPipelinesAfterOptimisation(file: path, type: type, source: .clipboard, optimiser: optimiser)
                            }
                        }
                    } else {
                        Task.init {
                            let type: ItemType = .audio(UTType.from(filePath: path) ?? .mp3)
                            var resultPath = path
                            if let result = try? await runAudioPipeline(Audio(path: path), actions: [.optimise], source: .clipboard) {
                                resultPath = result.path
                            }
                            if let optimiser = opt(path.string) {
                                await runPipelinesAfterOptimisation(file: resultPath, type: type, source: .clipboard, optimiser: optimiser)
                            }
                        }
                    }
                    return
                }
                if item.existingFilePath?.isAudio ?? false {
                    return
                }
                if item.types.contains(.photosReferenceAsset) {
                    optimiseClipboardPhotos()
                    return
                }
                optimiseClipboardImage(item: item)
            }
        }

        clipboardWatcher?.tolerance = 100
    }

    @objc func statusBarButtonClicked(_ sender: NSClickGestureRecognizer) {
        mainActor {
            if OM.skippedBecauseNotPro.isNotEmpty {
                OM.ignoreProErrorBadge = true
                sender.isEnabled = false

                guard let button = sender.view as? NSStatusBarButton else { return }
                button.performClick(self)
            }
        }
    }
}

var statusItem: NSStatusItem? {
    NSApp.windows.lazy.compactMap { window in
        window.perform(Selector(("statusItem")))?.takeUnretainedValue() as? NSStatusItem
    }.first
}

extension NSPasteboardItem {
    var existingFilePath: FilePath? {
        string(forType: .fileURL)?.fileURL?.existingFilePath ?? string(forType: .string)?.fileURL?.existingFilePath
    }
    var filePath: FilePath? {
        string(forType: .fileURL)?.fileURL?.filePath ?? string(forType: .string)?.fileURL?.filePath
    }
    var url: URL? {
        string(forType: .URL)?.url
    }
}

@MainActor func proLimitsReached(url: URL? = nil) {
    guard !Defaults[.neverShowProError] else {
        if let url, !OM.skippedBecauseNotPro.contains(url) {
            OM.skippedBecauseNotPro = OM.skippedBecauseNotPro.suffix(4).with(url)
        }
        if OM.skippedBecauseNotPro.isNotEmpty {
            let onclick = NSClickGestureRecognizer(target: AppDelegate.instance, action: #selector(AppDelegate.statusBarButtonClicked(_:)))
            statusItem?.button?.addGestureRecognizer(onclick)
        }

        return
    }

    let optimiser = OM.optimiser(id: Optimiser.IDs.pro, type: .unknown, operation: "")
    optimiser.finish(error: "You've optimised 5 files this session", notice: "Get Clop Pro to remove the limit and unlock all features.\nRelaunch the app to reset the counter.", keepFor: 5000)
}

let floatingResultsWindow = OSDWindow(swiftuiView: FloatingResultContainer().any, level: .floating, canScreenshot: Defaults[.allowClopToAppearInScreenshots], allowsMouse: true)
let cursorDropZoneWindow = OSDWindow(swiftuiView: DropZoneView().any, level: .floating, canScreenshot: Defaults[.allowClopToAppearInScreenshots], allowsMouse: true)
var clipboardWatcher: Timer?
var pbChangeCount = NSPasteboard.general.changeCount
let THUMB_SIZE = CGSize(width: 300, height: 220)

func migrateSettings() {
    guard let id = Bundle.main.bundleIdentifier else {
        return
    }

    let currentPrefs = URL.libraryDirectory
        .appendingPathComponent("Preferences")
        .appendingPathComponent(id == "com.lowtechguys.Clop-setapp" ? "com.lowtechguys.Clop-setapp.plist" : "com.lowtechguys.Clop.plist")
    let oldPrefs = URL.libraryDirectory
        .appendingPathComponent("Preferences")
        .appendingPathComponent(id == "com.lowtechguys.Clop-setapp" ? "com.lowtechguys.Clop.plist" : "com.lowtechguys.Clop-setapp.plist")

    if !FileManager.default.fileExists(atPath: currentPrefs.path), FileManager.default.fileExists(atPath: oldPrefs.path) {
        try? FileManager.default.copyItem(at: oldPrefs, to: currentPrefs)
        NSUbiquitousKeyValueStore.default.synchronize()
        restart()
    }
}

/// Seed the unified per-format `CompressionQuality` keys from the legacy aggressive/adaptive/encoder/bitrate
/// settings so existing users keep identical behaviour. Each version block runs exactly once; adding a new
/// block (for another format) never re-runs the earlier ones.
@MainActor func migrateToUnifiedCompression() {
    if Defaults[.compressionModelMigratedVersion] < 1 {
        // IMAGE: collapse the three per-format aggressive bools into one factor (any aggressive -> 64),
        // and map adaptiveImageSize onto the Adaptive tier.
        let anyAggressive = Defaults[.useAggressiveOptimisationJPEG]
            || Defaults[.useAggressiveOptimisationPNG]
            || Defaults[.useAggressiveOptimisationGIF]
        Defaults[.imageCompression] = CompressionQuality(
            tier: Defaults[.adaptiveImageSize] ? .adaptive : .custom,
            factor: anyAggressive ? COMPRESSION_FACTOR_AGGRESSIVE : COMPRESSION_FACTOR_NORMAL
        )
        Defaults[.compressionModelMigratedVersion] = 1
    }
    if Defaults[.compressionModelMigratedVersion] < 2 {
        // AUDIO: map the legacy absolute bitrate onto the factor for the current output format.
        // Negative sentinels (-1/-2 = "N steps lower than input") fall back to the default factor.
        let bitrate = Defaults[.audioBitrate]
        let factor = bitrate > 0 ? audioCompressionFactor(forBitrate: bitrate, format: Defaults[.audioFormat]) : 35
        Defaults[.audioCompression] = CompressionQuality(tier: .custom, factor: factor)
        Defaults[.compressionModelMigratedVersion] = 2
    }
}

let WINDOW_MIN_SIZE = CGSize(width: 870, height: 750)

// MARK: - ClopApp

@main
struct ClopApp: App {
    init() {
        migrateSettings()
    }

    @NSApplicationDelegateAdaptor(AppDelegate.self) var appDelegate

    @Environment(\.openWindow) var openWindow
    @Environment(\.dismiss) var dismiss
    @Environment(\.scenePhase) var scenePhase

    @AppStorage("showMenubarIcon") var showMenubarIcon = Defaults[.showMenubarIcon]

    @ObservedObject var om = OM
    @ObservedObject var wm = WM

    @ObservedObject var pm = PM

    var settingsWindow: some Scene {
        let w = Window("Settings", id: "settings") {
            SettingsView()
                .frame(minWidth: WINDOW_MIN_SIZE.width, maxWidth: .infinity, minHeight: WINDOW_MIN_SIZE.height, maxHeight: .infinity)
        }
        .windowStyle(.hiddenTitleBar)
        .windowResizability(.contentMinSize)
        .commands {
            CommandGroup(replacing: .help) {}
        }

        if #available(macOS 15.0, *) {
            return w
                .windowToolbarLabelStyle(fixed: .titleAndIcon)
        } else {
            return w
        }
    }

    var body: some Scene {
        MenuBarExtra(isInserted: $showMenubarIcon, content: {
            MenuView()
        }, label: {
            SwiftUI.Image(nsImage: NSImage(resource: !proactive && !om.ignoreProErrorBadge && om.skippedBecauseNotPro.isNotEmpty ? .menubarIconBadge : .menubarIcon))
        })
        .menuBarExtraStyle(.menu)
        .onChange(of: showMenubarIcon) { show in
            if !show {
                openWindow(id: "settings")
                focus()
            } else {
                NSApplication.shared.keyWindow?.close()
            }
        }
        .onChange(of: wm.windowToOpen) { window in
            guard let window else { return }
            openWindow(id: window)
            focus()
            NSApp.keyWindow?.orderFrontRegardless()
            wm.windowToOpen = nil
        }

        settingsWindow
            .handlesExternalEvents(matching: ["openSettings"])

    }
}

extension NSFilePromiseReceiver {
    static let swizzleReceivePromisedFiles: String = {
        let originalSelector = #selector(receivePromisedFiles(atDestination:options:operationQueue:reader:))
        let swizzledSelector = #selector(swizzledReceivePromisedFiles(atDestination:options:operationQueue:reader:))

        guard let originalMethod = class_getInstanceMethod(NSFilePromiseReceiver.self, originalSelector),
              let swizzledMethod = class_getInstanceMethod(NSFilePromiseReceiver.self, swizzledSelector)
        else {
            return "Swizzling NSFilePromiseReceiver.receivePromisedFiles() failed"

        }

        method_exchangeImplementations(originalMethod, swizzledMethod)
        return "Swizzled NSFilePromiseReceiver.receivePromisedFiles()"
    }()

    @objc private func swizzledReceivePromisedFiles(atDestination destinationDir: URL, options: [AnyHashable: Any] = [:], operationQueue: OperationQueue, reader: @escaping (URL, Error?) -> Void) {
        let exc = tryBlock {
            self.swizzledReceivePromisedFiles(atDestination: destinationDir, options: options, operationQueue: operationQueue, reader: reader)
        }
        guard let exc else {
            return
        }
        log.error("\(exc.description)")
    }
}

import Paddle

var PRODUCTS: [Any] {
    if let product {
        [product]
    } else {
        []
    }
}

extension NSView {
    static func swizzleDragFormation() {
        guard let NSDragDestination = NSClassFromString("NSDragDestination"),
              let originalMethod = class_getInstanceMethod(NSDragDestination, NSSelectorFromString("_draggingEntered"))
        else {
            return
        }

        let imp = method_getImplementation(originalMethod)

        method_setImplementation(originalMethod, imp_implementationWithBlock({ (self: NSDraggingInfo) in
            self.draggingFormation = .pile
            typealias MyCFunction = @convention(c) (NSDraggingInfo, Selector) -> Void
            let myImp = unsafeBitCast(imp, to: MyCFunction.self)
            return myImp(self, NSSelectorFromString("_draggingEntered"))
        } as @convention(block) (NSDraggingInfo) -> Void))
    }
}

class ContextualMenuServiceProvider: NSObject {
    @objc func stripEXIFService(_ pasteboard: NSPasteboard, userData: String?, error: AutoreleasingUnsafeMutablePointer<NSString>) {
        guard let items = pasteboard.pasteboardItems, !items.isEmpty else {
            return
        }
        for item in items.compactMap(\.existingFilePath) {
            stripExifOperationQueue.addOperation {
                item.stripExif()
            }
        }

        stripExifOperationQueue.waitUntilAllOperationsAreFinished()
    }

    @objc func optimisationService(_ pasteboard: NSPasteboard, userData: String?, error: AutoreleasingUnsafeMutablePointer<NSString>) {
        guard let items = pasteboard.pasteboardItems, !items.isEmpty else {
            return
        }

        for item in items.map(ClipboardType.fromPasteboardItem) {
            guard item != .unknown else {
                continue
            }
            Task.init {
                try await optimiseItem(
                    item,
                    id: item.id,
                    hideFloatingResult: false,
                    downscaleTo: nil,
                    changePlaybackSpeedBy: nil,
                    aggressiveOptimisation: nil,
                    optimisationCount: &manualOptimisationCount,
                    copyToClipboard: false,
                    source: .service
                )
            }
        }
    }
}

func defaultAppForUTI(_ uti: String) -> String? {
    guard let value = LSCopyDefaultRoleHandlerForContentType(uti as CFString, [LSRolesMask.viewer, LSRolesMask.editor]) else {
        return nil
    }
    return value.takeRetainedValue() as String
}
func setDefaultAppForUTI(_ uti: String, _ bundleID: String) -> OSStatus {
    LSSetDefaultRoleHandlerForContentType(uti as CFString, [LSRolesMask.viewer, LSRolesMask.editor], bundleID as CFString)
}
func resetDefaultPlayer() {
    if let mp4Player = defaultAppForUTI("public.mpeg-4"), mp4Player.starts(with: "com.lowtechguys.Clop") {
        _ = setDefaultAppForUTI("public.mpeg-4", "com.apple.QuickTimePlayerX")
    }
    if let movPlayer = defaultAppForUTI("com.apple.quicktime-movie"), movPlayer.starts(with: "com.lowtechguys.Clop") {
        _ = setDefaultAppForUTI("com.apple.quicktime-movie", "com.apple.QuickTimePlayerX")
    }
}
