//
//  ClopApp.swift
//  Clop
//
//  Created by Alin Panaitiu on 16.07.2022.
//

import Atomics
import Cocoa
import Combine
import Defaults
import Foundation
import Ignore
import Lowtech
import LowtechIndie
import LowtechPro
import LowtechProSentry
import os
import QuickLookUI
import Sentry
import ServiceManagement
import Sparkle
import SwiftUI
import System
import UniformTypeIdentifiers

private let log = Logger(subsystem: LOG_SUBSYSTEM, category: "ClopApp")

func clopDebugLog(_ message: String, includeCallStack: Bool = false) {
    guard let bid = Bundle.main.bundleIdentifier, bid.hasPrefix("com.lowtechguys.Clop") else { return }

    let df = DateFormatter()
    df.dateFormat = "yyyy-MM-dd HH:mm:ss.SSS"
    var line = "[\(df.string(from: Date()))] \(message)\n"
    if includeCallStack {
        line += Thread.callStackSymbols.joined(separator: "\n") + "\n"
    }
    let path = (NSHomeDirectory() as NSString).appendingPathComponent(".clop-debug-logs")
    if let handle = FileHandle(forWritingAtPath: path) {
        handle.seekToEndOfFile()
        handle.write(line.data(using: .utf8)!)
        handle.closeFile()
    } else {
        FileManager.default.createFile(atPath: path, contents: line.data(using: .utf8)!)
    }
}

var pauseForNextClipboardEvent = false

class WindowManager: ObservableObject {
    @Published var windowToOpen: String? = nil

    func open(_ window: String) {
        windowToOpen = window
    }
}
let WM = WindowManager()

/// Open the Settings window on the About tab and present the Paddle licence dialog as a sheet
/// attached to it. The Settings window opens asynchronously, so wait for it to exist before asking
/// Paddle to present — otherwise `AppDelegate.willShowPaddle` finds no parent window and the dialog
/// falls back to a standalone (previously unclickable) window.
@MainActor func manageLicenceInSettings() {
    settingsViewManager.tab = .about
    WM.open("settings")
    focus()

    func present(retriesLeft: Int) {
        if let window = NSApp.windows.first(where: { $0.isSettingsWindow }) {
            window.makeKeyAndOrderFront(nil)
            PRO?.manageLicence()
        } else if retriesLeft > 0 {
            mainAsyncAfter(ms: 50) { present(retriesLeft: retriesLeft - 1) }
        }
    }
    present(retriesLeft: 20)
}

var TRANSIENT_TYPES: Set<NSPasteboard.PasteboardType> = [
    .init("org.nspasteboard.TransientType"),
    .init("org.nspasteboard.ConcealedType"),
    .init("org.nspasteboard.AutoGeneratedType"),
]

extension NSPasteboard {
    func debug() {
        #if DEBUG
            print(name.rawValue)
            guard let pasteboardItems else {
                print("No items")
                return
            }
            for item in pasteboardItems {
                item.types.filter { ![NSPasteboard.PasteboardType.rtf, NSPasteboard.PasteboardType(rawValue: "public.utf16-external-plain-text")].contains($0) }.forEach { type in
                    print(type.rawValue + " " + (item.string(forType: type) ?! String(describing: item.propertyList(forType: type) ?? item.data(forType: type) ?? "<EMPTY DATA>")))
                }
            }
        #endif
    }
}

typealias AppDelegateParent = LowtechProAppDelegate

enum OptimisationSource: Codable, Equatable, Hashable {
    case clipboard
    case service
    case photos
    case openWith
    case fileWatcher
    case shortcuts
    case cli
    case dropZone
    case finder
    case dir(String)

    var string: String {
        switch self {
        case .clipboard: "clipboard"
        case .service: "service"
        case .photos: "photos"
        case .openWith: "openWith"
        case .fileWatcher: "fileWatcher"
        case .shortcuts: "shortcuts"
        case .cli: "cli"
        case .dropZone: "dropZone"
        case .finder: "finder"
        case let .dir(dir): dir
        }
    }

    var displayLabel: String {
        switch self {
        case .clipboard: "Clipboard"
        case .service: "Service"
        case .photos: "Photos"
        case .openWith: "Open With"
        case .fileWatcher: "Folder watcher"
        case .shortcuts: "Shortcuts"
        case .cli: "Command line"
        case .dropZone: "Drop zone"
        case .finder: "Finder"
        case let .dir(dir): FilePath(dir).lastComponent?.string ?? dir
        }
    }
}

extension String {
    var optSource: OptimisationSource? {
        switch self {
        case "clipboard": .clipboard
        case "service": .service
        case "photos": .photos
        case "shortcuts": .shortcuts
        case "cli": .cli
        case "finder": .finder
        case "openWith", "open-with", "open with": .openWith
        case "fileWatcher", "file-watcher", "file watcher": .fileWatcher
        case "dropZone", "drop-zone", "drop zone": .dropZone
        default: .dir(self)
        }
    }
}

/// Determine which app placed the current clipboard content, for the `copiedBy` pipeline filter.
/// Prefers the explicit `org.nspasteboard.source` bundle id, then the last-focused / frontmost app.
@MainActor func clipboardSourceApp(item: NSPasteboardItem?) -> (bundleID: String?, name: String?) {
    if let bundleID = item?.string(forType: NSPasteboard.PasteboardType("org.nspasteboard.source")), !bundleID.isEmpty {
        let name = NSWorkspace.shared.urlForApplication(withBundleIdentifier: bundleID).flatMap { Bundle(url: $0)?.name }
        return (bundleID, name)
    }
    if let id = LastFocusedAppTracker.shared.bundleId {
        return (id, LastFocusedAppTracker.shared.name)
    }
    let app = NSWorkspace.shared.frontmostApplication
    return (app?.bundleIdentifier, app?.localizedName)
}

/// Sentry's handler (installed by configureSentry) is captured here so we can chain to it. The
/// NSSetUncaughtExceptionHandler callback is a non-capturing C function pointer, so the previous
/// handler has to live in a global rather than be captured in the closure.
private var previousUncaughtExceptionHandler: (@convention(c) (NSException) -> Void)?

/// Record uncaught Objective-C exceptions with their name + reason before the process dies.
///
/// `NSApplicationCrashOnExceptions` is on (set by `configureSentry`), so exceptions thrown during
/// AppKit event dispatch are re-raised and reach this handler. Sentry's automatic capture buckets
/// them all into one frameless "reportException" issue; capturing here with a fingerprint built from
/// the exception name + reason splits that catch-all into actionable, distinct issues. Must be
/// installed after `configureSentry` so it chains to (instead of clobbering) Sentry's own handler.
func installUncaughtExceptionLogger() {
    previousUncaughtExceptionHandler = NSGetUncaughtExceptionHandler()
    NSSetUncaughtExceptionHandler { exception in
        let name = exception.name.rawValue
        let reason = exception.reason ?? "<no reason>"
        log.error("Uncaught NSException [\(name)]: \(reason)\n\(exception.callStackSymbols.joined(separator: "\n"))")
        SentrySDK.capture(exception: exception) { scope in
            scope.setFingerprint(["uncaught-nsexception", name, reason])
            scope.setTag(value: name, key: "exception_name")
        }
        SentrySDK.flush(timeout: 2)
        previousUncaughtExceptionHandler?(exception)
    }
}

class AppDelegate: AppDelegateParent {
    var proDebugCancellables = Set<AnyCancellable>()

    var videoWatcher: FileOptimisationWatcher?
    var imageWatcher: FileOptimisationWatcher?
    var pdfWatcher: FileOptimisationWatcher?
    var audioWatcher: FileOptimisationWatcher?

    @MainActor var swipeEnded = true

    @Setting(.floatingResultsCorner) var floatingResultsCorner
    lazy var draggingSet: PassthroughSubject<Bool, Never> = debouncer(in: &observers, every: .milliseconds(200)) { dragging in
        mainActor {
            DM.dragging = dragging
            if !dragging {
                DM.dropped = true
            } else {
                showFloatingThumbnails(force: true)
            }
        }
    }

    var lastDragChangeCount = NSPasteboard(name: .drag).changeCount

    @MainActor lazy var dragMonitor = GlobalEventMonitor(mask: [.leftMouseDragged]) { event in
        guard self.finishedOnboarding, NSEvent.pressedMouseButtons > 0, proactive || DM.optimisationCount <= 5 else {
            return
        }

        let drag = NSPasteboard(name: .drag)
//        drag.debug()
        guard self.lastDragChangeCount != drag.changeCount else {
            return
        }
        DM.dropped = false
        self.lastDragChangeCount = drag.changeCount

        guard let items = drag.pasteboardItems, !items.contains(where: { $0.types.set.hasElements(from: [.promise, .promisedFileName, .promisedFileURL, .promisedSuggestedFileName, .promisedMetadata]) }) else {
            DM.itemsToOptimise = []
            self.draggingSet.send(true)
            return
        }

        dropZoneKeyGlobalMonitor.start()
        dropZoneKeyLocalMonitor.start()
        presetZonesKeyGlobalMonitor.start()
        presetZonesKeyLocalMonitor.start()

        let toOptimise: [ClipboardType] = items.compactMap { item -> ClipboardType? in
            let types = item.types
            guard !types.contains(.init("com.apple.finalcutpro.xml")) else {
                return nil
            }

            if types.contains(.fileURL), let url = item.string(forType: .fileURL)?.url,
               let path = url.existingFilePath, path.isImage || path.isVideo || path.isAudio || path.isPDF
            {
                return .file(path)
            }

            if let str = item.string(forType: .string), let path = str.existingFilePath, path.isImage || path.isVideo || path.isAudio || path.isPDF {
                return .file(path)
            }

            if types.contains(.URL), let url = item.string(forType: .URL)?.url ?? item.string(forType: .string)?.url, url.isImage || url.isVideo || url.isPDF {
                return .url(url)
            }

            if types.set.hasElements(from: IMAGE_VIDEO_PASTEBOARD_TYPES) || types.contains(.pdf) {
                return .file(FilePath.tmp)
            }

            if let str = item.string(forType: .string), let url = str.url, url.isImage || url.isVideo || url.isPDF {
                return .url(url)
            }

            return nil
        }

        guard toOptimise.isNotEmpty else {
            DM.itemsToOptimise = []
            return
        }

        DM.itemsToOptimise = toOptimise
        self.draggingSet.send(true)
    }

    @MainActor lazy var mouseUpMonitor = GlobalEventMonitor(mask: [.leftMouseUp]) { event in
        self.draggingSet.send(false)
        if !DM.dragHovering, DM.itemsToOptimise.isNotEmpty {
            DM.dragging = false
            DM.itemsToOptimise = []
        }
    }

    @Setting(.optimiseVideoClipboard) var optimiseVideoClipboard

    var machPortThread: Thread?
    var machPortStopThread: Thread?

    var finishedOnboarding = Defaults[.finishedOnboarding] || Defaults[.launchCount] > 5

    lazy var onboardingWindowController: NSWindowController? = {
        let window = NSWindow(contentViewController: NSHostingController(rootView: OnboardingView()))
        window.title = "Onboarding"
        window.identifier = ONBOARDING_WINDOW_IDENTIFIER
        window.titleVisibility = .hidden
        window.titlebarAppearsTransparent = true
        window.styleMask = [.closable, .resizable, .titled]
        window.center()
        let wc = NSWindowController(window: window)
        window.windowController = wc

        return wc
    }()

    var sentryCrashExceptionApplicationType: AnyClass?

    var fileCleaner: Timer?

    @MainActor
    override func willShowPaddle(_ uiType: PADUIType, product _: PADProduct) -> PADDisplayConfiguration? {
        // Present the licence / product-access dialogs as a sheet on the Settings window when it is
        // open: as standalone windows they were sometimes not clickable. Checkout and alerts keep
        // their own window.
        if uiType == .product || uiType == .license, let settingsWindow = NSApp.windows.first(where: { $0.isSettingsWindow }) {
            settingsViewManager.tab = .about
            focus()
            settingsWindow.makeKeyAndOrderFront(nil)
            return PADDisplayConfiguration(.sheet, hideNavigationButtons: false, parentWindow: settingsWindow)
        }
        return PADDisplayConfiguration(.window, hideNavigationButtons: false, parentWindow: nil)
    }

    override func applicationDidFinishLaunching(_ notification: Notification) {
        sentryCrashExceptionApplicationType = SentryCrashExceptionApplication.self
        if !SWIFTUI_PREVIEW {
            handleCLIInstall()

            NSApplication.shared.windows.first { $0.isSettingsWindow }?.close()
            unarchiveBinaries()
            print(NSFilePromiseReceiver.swizzleReceivePromisedFiles)
            NSView.swizzleDragFormation()
            swizzleDraggableToRealPath()
            shouldRestartOnCrash = true

            NSRunningApplication.runningApplications(withBundleIdentifier: Bundle.main.bundleIdentifier!)
                .filter { $0.processIdentifier != ProcessInfo.processInfo.processIdentifier }
                .forEach {
                    $0.forceTerminate()
                }
            let _ = shell("/usr/bin/pkill", args: ["-fl", "Clop/bin/(arm64|x86)/.+"], wait: false)
            signal(SIGTERM) { _ in
                for opt in OM.optimisers + OM.removedOptimisers {
                    opt.stop(animateRemoval: false)
                }
                exit(0)
            }
            signal(SIGKILL) { _ in
                for opt in OM.optimisers + OM.removedOptimisers {
                    opt.stop(animateRemoval: false)
                }
                exit(0)
            }

            syncSettings()
            _ = LastFocusedAppTracker.shared
            Defaults[.cliInstalled] = cliSymlinkValid()
            Migrations.run()
            createFileCleaner()
        }

        paddleVendorID = "122873"
        paddleAPIKey = "e1e517a68c1ed1bea2ac968a593ac147"
        paddleProductID = "841006"
        trialDays = 14
        trialText = "This is a trial for the Pro features. After the trial, the app will automatically revert to the free version."
        price = 15
        productName = "Clop Pro"
        vendorName = "THE LOW TECH GUYS SRL"
        hasFreeFeatures = true

        if !SWIFTUI_PREVIEW {
            LowtechSentry.sentryDSN = "https://7dad9331a2e1753c3c0c6bc93fb0d523@o84592.ingest.sentry.io/4505673793077248"
            LowtechSentry.configureSentry(restartOnHang: false, getUser: LowtechSentry.getSentryUser)
            installUncaughtExceptionLogger()
            configureAppHangDetection { _, _ in
                activeCLIRequests.load(ordering: .relaxed) > 0 ? .suppressRestart : .useDefault
            }

            KM.primaryKeyModifiers = Defaults[.keyComboModifiers]
            KM.primaryKeys = Defaults[.enabledKeys] + Defaults[.quickResizeKeys]
            KM.onPrimaryHotkey = { key in
                self.handleHotkey(key)
                let _ = invalidReq2(PRODUCTS, nil)
            }

            KM.secondaryKeyModifiers = [.lcmd]
            KM.onSecondaryHotkey = { key in
                self.handleCommandHotkey(key)
                let _ = invalidReq3(PRODUCTS, nil)
            }

            KM.onBareHotkey = { key in
                self.handleBareHotkey(key)
            }
        }
        super.applicationDidFinishLaunching(_: notification)
        UM.updater = updateController.updater
        PM.pro = pro
        if !SWIFTUI_PREVIEW {
            clopDebugLog("applicationDidFinishLaunching: about to checkProLicense (productActivated=\(pro.productActivated), onTrial=\(pro.onTrial))")
            pro.checkProLicense()
        }

        let p = pro
        p.$productActivated.sink { newValue in
            clopDebugLog("proactive observer: productActivated changed to \(newValue) (onTrial=\(p.onTrial), proactive will be \(newValue || p.onTrial))")
        }.store(in: &proDebugCancellables)
        p.$onTrial.sink { newValue in
            clopDebugLog("proactive observer: onTrial changed to \(newValue) (productActivated=\(p.productActivated), proactive will be \(p.productActivated || newValue))")
        }.store(in: &proDebugCancellables)

        Defaults[.videoDirs] = Defaults[.videoDirs].filter { fm.fileExists(atPath: $0) }
        migrateShortcutsToPipelines()
        migrateToUnifiedCompression()
        seedBuiltinPipelines()

        guard !SWIFTUI_PREVIEW else { return }

        floatingResultsWindow.animateOnResize = false
        pub(.allowClopToAppearInScreenshots)
            .sink {
                floatingResultsWindow.sharingType = $0.newValue ? .readOnly : .none
            }
            .store(in: &observers)
        pub(.workdir)
            .sink {
                FilePath.workdir = FilePath.dir($0.newValue, permissions: 0o777)
            }
            .store(in: &observers)
        pub(.floatingResultsCorner)
            .sink {
                floatingResultsWindow.screenCorner = $0.newValue
                floatingResultsWindow.moveToScreen(.withMouse, corner: $0.newValue)
            }
            .store(in: &observers)
        pub(.keyComboModifiers)
            .sink {
                KM.primaryKeyModifiers = $0.newValue
                KM.reinitHotkeys()
            }
            .store(in: &observers)
        pub(.quickResizeKeys)
            .sink {
                KM.primaryKeys = Defaults[.enabledKeys] + $0.newValue
                KM.reinitHotkeys()
            }
            .store(in: &observers)
        pub(.enabledKeys)
            .sink {
                KM.primaryKeys = $0.newValue + Defaults[.quickResizeKeys]
                KM.reinitHotkeys()
            }
            .store(in: &observers)
        pub(.enableFloatingResults)
            .sink {
                if $0.newValue {
                    showFloatingThumbnails(force: true)
                } else {
                    floatingResultsWindow.close()
                }
            }
            .store(in: &observers)

        if finishedOnboarding {
            initOptimisers()
        } else {
            onboardFileOptimisation()
        }
        trackScrollWheel()

        if Defaults[.enableDragAndDrop] {
            dragMonitor.start()
            mouseUpMonitor.start()
        }
        pub(.enableDragAndDrop)
            .sink { enabled in
                if enabled.newValue {
                    self.dragMonitor.start()
                    self.mouseUpMonitor.start()
                } else {
                    self.dragMonitor.stop()
                    self.mouseUpMonitor.stop()
                }
            }
            .store(in: &observers)
        pub(.enableClipboardOptimiser)
            .sink { enabled in
                if enabled.newValue {
                    self.initClipboardOptimiser()
                } else {
                    clipboardWatcher?.cancel()
                }
            }
            .store(in: &observers)
        pub(.pauseAutomaticOptimisations)
            .sink { paused in
                if paused.newValue {
                    clipboardWatcher?.cancel()
                } else {
                    self.initClipboardOptimiser()
                }
            }
            .store(in: &observers)
        initMachPortListener()

        _ = invalidReq(PRODUCTS, nil)
        setupServiceProvider()
        startShortcutWatcher()
        DROPSHARE.fetchAppURL()
        DROPOVER.fetchAppURL()
        YOINK.fetchAppURL()
        DOCKSIDE.fetchAppURL()
        ATOLL.fetchAppURL()

        // listen for NSWindow.willCloseNotification to release the window
        NotificationCenter.default.addObserver(self, selector: #selector(windowWillClose), name: NSWindow.willCloseNotification, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(windowDidBecomeMainNotification), name: NSWindow.didBecomeMainNotification, object: nil)
    }

    override func applicationDidBecomeActive(_ notification: Notification) {
        didBecomeActiveAtLeastOnce = true
    }

    @MainActor
    static func handleStopOptimisationRequest(_ req: StopOptimisationRequest) {
        log.debug("Stopping optimisation request: \(req.jsonString)")

        for id in req.ids {
            guard let opt = opt(id) else {
                continue
            }

            opt.stop(remove: req.remove)
            opt.uiStop()
        }
    }

    static func handleOptimisationRequest(_ req: OptimisationRequest) -> Data? {
        log.debug("Handling optimisation request: \(req.jsonString)")

        activeCLIRequests.wrappingIncrement(ordering: .relaxed)
        defer { activeCLIRequests.wrappingDecrement(ordering: .relaxed) }

        let sem = DispatchSemaphore(value: 0)
        var resp: [OptimisationResponse] = []
        tryAsync {
            resp = try await processOptimisationRequest(req)
            sem.signal()
        }
        sem.wait()

        return resp.jsonData
    }

    func allowedChannels(for _: SPUUpdater) -> Set<String> {
        lowtechAllowedChannels()
    }

    func application(_ application: NSApplication, open urls: [URL]) {
        Task {
            await handleURLs(application, urls)
        }
    }

    func application(_ sender: NSApplication, openFiles filenames: [String]) {
        Task {
            await handleURLs(sender, filenames.compactMap(\.url))
        }
    }

    func handleURLs(_ application: NSApplication, _ urls: [URL]) async {
        do {
            try await withThrowingTaskGroup(of: Void.self, returning: Void.self) { group in
                for item in urls.map(ClipboardType.fromURL(_:)) {
                    let source: OptimisationSource = item.path.string.contains("com.apple.Photos") ? .photos : .openWith
                    let added = group.addTaskUnlessCancelled {
                        try await optimiseItem(
                            item,
                            id: item.id,
                            adaptiveOptimisation: false,
                            optimisationCount: &manualOptimisationCount,
                            copyToClipboard: false,
                            source: source,
                            removeAudio: false,
                            optimisedFileBehaviour: source == .photos ? .inPlace : nil
                        )
                    }
                    guard added else { break }
                    try await group.next()
                }
            }
        } catch {
            log.error("Error optimising files from 'Open with': \(error.localizedDescription)")
            application.reply(toOpenOrPrint: .failure)
        }
        application.reply(toOpenOrPrint: .success)
    }

    func setupServiceProvider() {
        NSApp.registerServicesMenuSendTypes([.png, .pdf, .fileURL, .fileContents], returnTypes: [.png, .pdf, .fileURL, .fileContents])
        NSApplication.shared.servicesProvider = ContextualMenuServiceProvider()
        NSUpdateDynamicServices()
    }

    @MainActor
    func handleCommandHotkey(_ key: SauceKey) {
        guard finishedOnboarding, let opt = OM.hovered else {
            return
        }

        switch key {
        case .comma:
            WM.open("settings")
            focus()
        case .minus:
            // Step "down" maps to each type's own compression axis: DPI for PDF, bitrate for audio,
            // resolution for everything else. stepDownscale only drives image/video, so PDF/audio
            // need their dedicated steppers or the keypress just flashes the indicator.
            if opt.type.isPDF {
                opt.stepLowerPDFDPI()
            } else if opt.type.isAudio {
                opt.stepLowerBitrate()
            } else if opt.downscaleFactor > 0.1 {
                opt.stepDownscale()
            }
        case .x where opt.changePlaybackSpeedFactor < 10 && opt.canChangePlaybackSpeed():
            opt.changePlaybackSpeed()
        case .delete:
            hoveredOptimiserID = nil
            opt.stop(animateRemoval: true)
        case .z where !opt.isOriginal:
            opt.restoreOriginal()
            opt.overlayMessage = "Restored original"
            opt.collapseHoverOverlay = true
        case .r where !opt.running:
            opt.editingFilename = true
        case .d where opt.url != nil && opt.comparisonOriginalURL != nil:
            opt.compare()
        case .k where opt.canCrop() && !opt.running:
            opt.showCropWindow()
        case .c:
            opt.copyToClipboard()
            opt.overlayMessage = "Copied"
        case .s:
            opt.save()
        case .f:
            opt.showInFinder()
        case .u:
            DROPSHARE.open(optimiser: opt)
        case .w:
            if let session = WDM.session(forOptimiser: opt) {
                session.copyLink()
                opt.overlayMessage = "Copied link"
            } else {
                warpDropSend(optimiser: opt)
            }
        case .o:
            guard let url = opt.url ?? opt.originalURL else { return }
            NSWorkspace.shared.open(url)
        case .a where !opt.aggressive:
            if opt.downscaleFactor < 1 {
                opt.downscale(toFactor: opt.downscaleFactor, aggressiveOptimisation: true)
            } else {
                opt.optimise(allowLarger: false, aggressiveOptimisation: true, fromOriginal: true)
            }
        default:
            return
        }
    }

    /// Plain Space pressed while hovering a floating result: toggle QuickLook.
    /// Returns false to forward the keypress to the focused app instead.
    func handleBareHotkey(_ key: SauceKey) -> Bool {
        guard key == .space, finishedOnboarding, !SM.selecting,
              let opt = OM.hovered, !opt.editingFilename
        else {
            return false
        }

        if QLPreviewPanel.sharedPreviewPanelExists(), let ql = QLPreviewPanel.shared(), ql.isVisible {
            ql.close()
        } else {
            opt.quicklook()
        }
        return true
    }

    @MainActor
    func handleHotkey(_ key: SauceKey) {
        guard finishedOnboarding else { return }

        switch key {
        case .escape:
            OM.clearVisibleOptimisers(stop: true)
        case .minus:
            if let opt = OM.current {
                if opt.type.isPDF {
                    opt.stepLowerPDFDPI()
                } else if opt.type.isAudio {
                    opt.stepLowerBitrate()
                } else if opt.downscaleFactor > 0.1 {
                    opt.stepDownscale()
                }
            } else {
                guard scalingFactor > 0.1 else { return }
                scalingFactor = max(scalingFactor > 0.5 ? scalingFactor - 0.25 : scalingFactor - 0.1, 0.1)
                Task { try? await optimiseLastClipboardItem(downscaleTo: scalingFactor) }
            }
        case .x:
            if let opt = OM.current, opt.canChangePlaybackSpeed() {
                guard opt.changePlaybackSpeedFactor < 10 else { return }
                opt.changePlaybackSpeed()
            } else {
                Task { try? await optimiseLastClipboardItem(changePlaybackSpeedBy: 1.25) }
            }
        case .r:
            if let opt = OM.current, !opt.running {
                opt.editingFilename = true
            }
        case .k:
            if let opt = OM.current, opt.canCrop(), !opt.running {
                opt.showCropWindow()
            }
        case .delete:
            if let opt = OM.optimisers.filter({ !$0.inRemoval && !$0.hidden }).max(by: \.startedAt) {
                hoveredOptimiserID = nil
                opt.stop(animateRemoval: true)
            }
        case .equal:
            if let opt = OM.removedOptimisers.popLast() {
                opt.bringBack()
            }
        case .space:
            if let opt = OM.current, !opt.inRemoval {
                opt.quicklook()
            } else {
                Task { try? await quickLookLastClipboardItem() }
            }
        case .z:
            if let opt = OM.current, !opt.inRemoval, !opt.isOriginal {
                opt.restoreOriginal()
            }
        case .p:
            if Defaults[.pauseAutomaticOptimisations] {
                Defaults[.pauseAutomaticOptimisations] = false
                pauseForNextClipboardEvent = false
                showNotice("**Running** • Paused • Stopped\nClop is listening for clipboard and file events")
            } else if pauseForNextClipboardEvent {
                Defaults[.pauseAutomaticOptimisations] = true
                showNotice("Running • Paused • **Stopped**\nAll automatic optimisations are stopped")
            } else {
                pauseForNextClipboardEvent = true
                showNotice("Running • **Paused** • Stopped\nNext clipboard event will be ignored")
            }
        case .c:
            Task { try? await optimiseLastClipboardItem() }
        case .a:
            if let opt = OM.current, !opt.inRemoval {
                guard !opt.aggressive else { return }
                if opt.downscaleFactor < 1 {
                    opt.downscale(toFactor: opt.downscaleFactor, aggressiveOptimisation: true)
                } else {
                    opt.optimise(allowLarger: false, aggressiveOptimisation: true, fromOriginal: true)
                }
            } else {
                Task { try? await optimiseLastClipboardItem(aggressiveOptimisation: true) }
            }
        case SauceKey.NUMBER_KEYS.suffix(from: 1).arr:
            guard let number = key.QWERTYCharacter.d else { break }

            if let opt = OM.current, !opt.inRemoval {
                opt.downscale(toFactor: number / 10.0)
            } else {
                Task { try? await optimiseLastClipboardItem(downscaleTo: number / 10.0) }
            }
        default:
            break
        }
    }

    func syncSettings() {
        if Defaults[.syncSettingsCloud] {
            Zephyr.observe(keys: SETTINGS_TO_SYNC)
        }
        pub(.syncSettingsCloud)
            .sink { change in
                if change.newValue {
                    Zephyr.observe(keys: SETTINGS_TO_SYNC)
                } else {
                    Zephyr.stopObserving(keys: SETTINGS_TO_SYNC)
                }
            }.store(in: &observers)
    }
    func initMachPortListener() {
        machPortThread = Thread {
            OPTIMISATION_PORT.listen { data in
                guard let data else {
                    return nil
                }

                var result: Data? = nil
                if let req = OptimisationRequest.from(data) {
                    result = Self.handleOptimisationRequest(req)
                }

                guard let result else {
                    return nil
                }
                return Unmanaged.passRetained(result as CFData)
            }
            RunLoop.current.run()
        }
        machPortStopThread = Thread {
            OPTIMISATION_STOP_PORT.listen { data in
                guard let data, let req = StopOptimisationRequest.from(data) else {
                    return nil
                }

                mainActor { Self.handleStopOptimisationRequest(req) }
                return nil
            }
            RunLoop.current.run()
        }

        machPortThread?.start()
        machPortStopThread?.start()
    }

    func applicationWillFinishLaunching(_ notification: Notification) {
        if !SWIFTUI_PREVIEW {
            migrateSettings()
            resetDefaultPlayer()
        }
    }

    func createFileCleaner() {
        fileCleaner = Timer.scheduledTimer(withTimeInterval: 600, repeats: true) { _ in
            let interval = Defaults[.workdirCleanupInterval]
            guard interval != .never else {
                return
            }

            // NB: `FilePath.batchBackups` is intentionally absent here. Batch backups are the only
            // pristine copy after an in-place rewrite and are removed only via "Delete backups" or a
            // verified restore, never on the time-based schedule.
            for dir in [FilePath.clopBackups, .videos, .images, .pdfs, .conversions, .downloads, .forResize, .forFilters, .finderQuickAction, .processLogs] {
                let enumerator = fm.enumerator(at: dir.url, includingPropertiesForKeys: [.attributeModificationDateKey, .isDirectoryKey], options: [.skipsHiddenFiles, .skipsPackageDescendants])
                guard let iterator = enumerator else {
                    return
                }

                let now = Date()
                while case let url as URL = iterator.nextObject() {
                    if let isdir = try? url.resourceValues(forKeys: [.isDirectoryKey]).isDirectory, isdir {
                        continue
                    }
                    guard let date = try? url.resourceValues(forKeys: [.attributeModificationDateKey]).attributeModificationDate else {
                        continue
                    }

                    if now.timeIntervalSince(date) > interval.rawValue {
                        log.debug("Deleting \(url.path) because it's older than \(interval.title) (last modified \(date))")
                        try? fm.removeItem(at: url)
                    }
                }
            }
        }
        fileCleaner?.tolerance = 300
        fileCleaner?.fire()
    }

    @MainActor
    func onboardFileOptimisation() {
        print(OnboardingFloatingPreview.om)
        NSApp.setActivationPolicy(.regular)
        onboardingWindowController?.showWindow(self)
        focus()
    }

    /// `.regular` (Dock icon + Cmd-Tab) while any of the app's real windows is open; back to a menu-bar
    /// `.accessory` only once the last one closes. Cooperative, so closing one window (e.g. Settings)
    /// doesn't strand another that's still open (e.g. the batch window). During `windowWillClose` the
    /// closing window is still in `NSApp.windows`, so pass it as `excluding`.
    @MainActor func syncActivationPolicy(excluding closing: NSWindow? = nil) {
        let hasRealWindow = NSApp.windows.contains { w in
            w !== closing && (w.isVisible || w.isMiniaturized) && w.isActivatingAppWindow
        }
        NSApp.setActivationPolicy(hasRealWindow ? .regular : .accessory)
    }

    @objc func windowWillClose(_ notification: Notification) {
        guard let window = notification.object as? NSWindow else { return }

        if window.isSettingsWindow {
            mainActor { settingsViewManager.windowOpen = false }
        }

        if window.identifier == ONBOARDING_WINDOW_IDENTIFIER {
            mainActor {
                self.finishedOnboarding = true
                Defaults[.finishedOnboarding] = true
                self.initOptimisers()
                self.onboardingWindowController?.window = nil
                self.onboardingWindowController = nil
            }
        }

        if window.identifier == BATCH_WINDOW_IDENTIFIER {
            mainActor {
                // Closing the window stops any in-flight processing (originals stay restorable from
                // the backups, which persist until "Delete backups").
                BAT.cancel()
                BAT.windowController = nil
            }
        }

        // Keep the Dock icon + Cmd-Tab entry while any other real window is still open; only fall back
        // to a menu-bar accessory once the last one closes.
        mainActor { self.syncActivationPolicy(excluding: window) }
    }

    @objc func windowDidBecomeMainNotification(_ notification: Notification) {
        guard let window = notification.object as? NSWindow else { return }

        if let paddleController = window.windowController as? PADActivateWindowController,
           let email = paddleController.emailTxt, let licenseCode = paddleController.licenseTxt
        {
            email.isBordered = true
            licenseCode.isBordered = true

            email.drawsBackground = true
            licenseCode.drawsBackground = true

            email.backgroundColor = .black.withAlphaComponent(0.05)
            licenseCode.backgroundColor = .black.withAlphaComponent(0.05)
        }

        if window.title.contains("Updat") {
            focus()
            return
        }

        if window.isSettingsWindow {
            mainActor {
                print(FloatingPreview.om, CompactPreview.om)
                settingsViewManager.windowOpen = true

                log.debug("Starting settings tab key monitor")
                tabKeyMonitor.start()
            }
        }

        // Any of Clop's real windows (Settings, Batch, Comparison, Onboarding, Crop) becoming main
        // needs the app in `.regular` so it shows a Dock icon and a Cmd-Tab entry.
        if window.isActivatingAppWindow {
            NSApp.setActivationPolicy(.regular)
        }
    }

    func trackScrollWheel() {
        NSApp.publisher(for: \.currentEvent)
            .filter { event in event?.type == .scrollWheel }
            .throttle(
                for: .milliseconds(20),
                scheduler: DispatchQueue.main,
                latest: true
            )
            .sink { event in
                guard let event else { return }

                mainActor {
                    if self.swipeEnded, !OM.compactResults, self.floatingResultsCorner.isTrailing ? event.scrollingDeltaX > 3 : event.scrollingDeltaX < -3,
                       let hov = hoveredOptimiserID, let optimiser = OM.optimisers.first(where: { $0.id == hov })
                    {
                        hoveredOptimiserID = nil
                        optimiser.stop(remove: true, animateRemoval: true)
                        self.swipeEnded = false
                    }
                    if event.scrollingDeltaX == 0 {
                        self.swipeEnded = true
                    }
                }
            }.store(in: &observers)

        NSEvent.addLocalMonitorForEvents(matching: .keyDown) { event in
            guard let hov = hoveredOptimiserID,
                  let optimiser = OM.optimisers.first(where: { $0.id == hov }),
                  event.modifierFlags.contains(.command)
            else { return event }

            switch event.charactersIgnoringModifiers {
            case "e":
                // Prefer the user's configured "Edit with" app for this file type; fall back to the
                // running shelf app (Yoink/Dropover/…) when none is set.
                if optimiser.editWithConfiguredApp() { return nil }
                guard let shelfApp = runningShelfApp() else { return event }
                shelfApp.open(optimiser: optimiser)
                return nil
            case "f":
                optimiser.showInFinder()
                return nil
            default:
                return event
            }
        }
    }

    func applicationShouldHandleReopen(_: NSApplication, hasVisibleWindows _: Bool) -> Bool {
        // Fires when the app is launched again while already running (Finder double-click, dock
        // click, `open`), but NOT on plain re-activation like QuickLook making the app key, so
        // surfacing settings here means it won't pop up when you QuickLook a floating result.

        // If one of Clop's real windows is already open (e.g. the batch/crop/comparison window covered
        // by other apps' windows), a dock click should bring the frontmost one forward rather than
        // popping Settings on top of it.
        if let window = NSApp.orderedWindows.first(where: { ($0.isVisible || $0.isMiniaturized) && $0.isActivatingAppWindow }) {
            if window.isMiniaturized { window.deminiaturize(nil) }
            window.makeKeyAndOrderFront(nil)
            window.orderFrontRegardless()
            focus()
            return true
        }

        WM.open("settings")
        focus()
        return true
    }
    func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
        false
    }

    @MainActor func initOptimisers() {
        guard finishedOnboarding else { return }
        let debounceMS = Defaults[.launchCount] == 1 ? 800 : 100

        videoWatcher = FileOptimisationWatcher(
            pathsKey: .videoDirs,
            enabledKey: .enableAutomaticVideoOptimisations,
            maxFilesToHandleKey: .maxVideoFileCount,
            fileType: .video,
            shouldHandle: shouldHandleVideo(event:),
            cancel: cancelVideoOptimisation(path:)
        ) { path in
            guard OM.visibleOptimisers.first(where: { $0.running && $0.id == path.string }) == nil,
                  !OM.optimisers.contains(where: { $0.url?.path == path.string })
            else {
                return
            }
            Task {
                // Skip videos outside the resolution range (metadata is only fetched when a bound is set).
                let minRes = Defaults[.minVideoResolution]
                let maxRes = Defaults[.maxVideoResolution]
                if minRes > 0 || maxRes > 0, let video = try? await Video.byFetchingMetadata(path: path, thumb: false), let res = video.size {
                    if minRes > 0, res.width < CGFloat(minRes) || res.height < CGFloat(minRes) {
                        return
                    }
                    if maxRes > 0, res.width > CGFloat(maxRes) || res.height > CGFloat(maxRes) {
                        return
                    }
                }
                let matchedDir = Defaults[.videoDirs].filter { path.string.starts(with: $0) }.max(by: \.count)
                let source = matchedDir?.optSource
                let hide = matchedDir.map { Defaults[.dirsHideFloatingResult].contains($0) } ?? false
                let type: ItemType = .video(UTType.from(filePath: path) ?? .mpeg4Movie)
                let pipelines = source.map { pipelinesFor(type: type, source: $0) } ?? []
                let allSkip = !pipelines.isEmpty && pipelines.allSatisfy(\.skipsPreOptimisation)

                var resultPath = path
                if allSkip {
                    let optimiser = OM.optimiser(id: path.string, type: type, operation: "Running pipeline", hidden: true, source: source)
                    optimiser.url = path.url
                    if let source {
                        await runPipelinesAfterOptimisation(file: resultPath, type: type, source: source, optimiser: optimiser)
                    }
                } else {
                    let video = Video(path: path)
                    if let result = try? await runVideoPipeline(video, actions: [.optimise], debounceMS: debounceMS, hideFloatingResult: hide, source: source) {
                        resultPath = result.path
                    }
                    if let source, let optimiser = opt(path.string) {
                        await runPipelinesAfterOptimisation(file: resultPath, type: type, source: source, optimiser: optimiser)
                    }
                }
            }
        }
        imageWatcher = FileOptimisationWatcher(
            pathsKey: .imageDirs,
            enabledKey: .enableAutomaticImageOptimisations,
            maxFilesToHandleKey: .maxImageFileCount,
            fileType: .image,
            shouldHandle: shouldHandleImage(event:),
            cancel: cancelImageOptimisation(path:)
        ) { path in
            guard OM.visibleOptimisers.first(where: { $0.running && $0.id == path.string }) == nil,
                  !OM.optimisers.contains(where: { $0.url?.path == path.string })
            else {
                return
            }
            Task {
                let matchedDir = Defaults[.imageDirs].filter { path.string.starts(with: $0) }.max(by: \.count)
                let source = matchedDir?.optSource
                let hide = matchedDir.map { Defaults[.dirsHideFloatingResult].contains($0) } ?? false
                guard let img = Image(path: path, retinaDownscaled: false) else { return }
                let type: ItemType = .image(img.type)
                let pipelines = source.map { pipelinesFor(type: type, source: $0) } ?? []
                let allSkip = !pipelines.isEmpty && pipelines.allSatisfy(\.skipsPreOptimisation)

                var resultPath = path
                if allSkip {
                    let optimiser = OM.optimiser(id: path.string, type: type, operation: "Running pipeline", hidden: true, source: source)
                    optimiser.url = path.url
                    if let source {
                        await runPipelinesAfterOptimisation(file: resultPath, type: type, source: source, optimiser: optimiser)
                    }
                } else {
                    if let result = try? await runImagePipeline(img, actions: [.optimise], debounceMS: debounceMS, hideFloatingResult: hide, source: source) {
                        resultPath = result.path
                    }
                    if let source, let optimiser = opt(path.string) {
                        await runPipelinesAfterOptimisation(file: resultPath, type: type, source: source, optimiser: optimiser)
                    }
                }
            }
        }
        pdfWatcher = FileOptimisationWatcher(
            pathsKey: .pdfDirs,
            enabledKey: .enableAutomaticPDFOptimisations,
            maxFilesToHandleKey: .maxPDFFileCount,
            fileType: .pdf,
            shouldHandle: shouldHandlePDF(event:),
            cancel: cancelPDFOptimisation(path:)
        ) { path in
            guard OM.visibleOptimisers.first(where: { $0.running && $0.id == path.string }) == nil,
                  !OM.optimisers.contains(where: { $0.url?.path == path.string })
            else {
                return
            }
            Task {
                let matchedDir = Defaults[.pdfDirs].filter { path.string.starts(with: $0) }.max(by: \.count)
                let source = matchedDir?.optSource
                let hide = matchedDir.map { Defaults[.dirsHideFloatingResult].contains($0) } ?? false
                let type: ItemType = .pdf
                let pipelines = source.map { pipelinesFor(type: type, source: $0) } ?? []
                let allSkip = !pipelines.isEmpty && pipelines.allSatisfy(\.skipsPreOptimisation)

                var resultPath = path
                if allSkip {
                    let optimiser = OM.optimiser(id: path.string, type: type, operation: "Running pipeline", hidden: true, source: source)
                    optimiser.url = path.url
                    if let source {
                        await runPipelinesAfterOptimisation(file: resultPath, type: type, source: source, optimiser: optimiser)
                    }
                } else {
                    if let result = try? await runPDFPipeline(PDF(path), actions: [.optimise], debounceMS: debounceMS, hideFloatingResult: hide, source: source) {
                        resultPath = result.path
                    }
                    if let source, let optimiser = opt(path.string) {
                        await runPipelinesAfterOptimisation(file: resultPath, type: type, source: source, optimiser: optimiser)
                    }
                }
            }
        }
        audioWatcher = FileOptimisationWatcher(
            pathsKey: .audioDirs,
            enabledKey: .enableAutomaticAudioOptimisations,
            maxFilesToHandleKey: .maxAudioFileCount,
            fileType: .audio,
            shouldHandle: shouldHandleAudio(event:),
            cancel: cancelAudioOptimisation(path:)
        ) { path in
            guard OM.visibleOptimisers.first(where: { $0.running && $0.id == path.string }) == nil,
                  !OM.optimisers.contains(where: { $0.url?.path == path.string })
            else {
                return
            }
            Task {
                let matchedDir = Defaults[.audioDirs].filter { path.string.starts(with: $0) }.max(by: \.count)
                let source = matchedDir?.optSource
                let hide = matchedDir.map { Defaults[.dirsHideFloatingResult].contains($0) } ?? false
                let type: ItemType = .audio(UTType.from(filePath: path) ?? .mp3)
                let pipelines = source.map { pipelinesFor(type: type, source: $0) } ?? []
                let allSkip = !pipelines.isEmpty && pipelines.allSatisfy(\.skipsPreOptimisation)

                var resultPath = path
                if allSkip {
                    let optimiser = OM.optimiser(id: path.string, type: type, operation: "Running pipeline", hidden: true, source: source)
                    optimiser.url = path.url
                    if let source {
                        await runPipelinesAfterOptimisation(file: resultPath, type: type, source: source, optimiser: optimiser)
                    }
                } else {
                    if let result = try? await runAudioPipeline(Audio(path: path), actions: [.optimise], debounceMS: debounceMS, hideFloatingResult: hide, source: source) {
                        resultPath = result.path
                    }
                    if let source, let optimiser = opt(path.string) {
                        await runPipelinesAfterOptimisation(file: resultPath, type: type, source: source, optimiser: optimiser)
                    }
                }
            }
        }

        if Defaults[.enableClipboardOptimiser], !Defaults[.pauseAutomaticOptimisations] {
            initClipboardOptimiser()
        }

        _ = invalidReq(PRODUCTS, nil)
    }

    @MainActor func initClipboardOptimiser() {
        guard finishedOnboarding else { return }

        clipboardWatcher?.cancel()
        // Poll the pasteboard on a dedicated serial background queue instead of a main-runloop Timer.
        // `NSPasteboard.changeCount` and the content reads (`pasteboardItems`, `existingFilePath`, …)
        // are synchronous XPC round-trips to the pasteboard server; running them on the main thread
        // froze the UI for 30s+ whenever that server was slow (CLOP-A3, CLOP-AC). All pasteboard reads
        // stay on this one serial queue and we hop to the main actor only once a real change needs
        // handling, passing already-resolved values. `pbChangeCount` is owned by this queue;
        // `pauseForNextClipboardEvent` is checked on the main actor (where it's written) to avoid a race.
        let timer = DispatchSource.makeTimerSource(queue: clipboardQueue)
        timer.schedule(deadline: .now() + 0.5, repeating: 0.5, leeway: .milliseconds(100))
        timer.setEventHandler { [weak self] in
            guard let self else { return }

            let pb = NSPasteboard.general
            let newChangeCount = pb.changeCount
            guard newChangeCount != pbChangeCount else {
                return
            }
            pbChangeCount = newChangeCount

            guard let item = pb.pasteboardItems?.first, item.string(forType: .optimisationStatus) == nil, !TRANSIENT_TYPES.hasElements(from: Set(item.types)) else {
                return
            }

            let ignoredApps = Defaults[.clipboardIgnoredAppBundleIds]
            if !ignoredApps.isEmpty,
               let frontmostBundleID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier,
               ignoredApps.contains(frontmostBundleID)
            {
                return
            }

            // Resolve everything that needs the pasteboard here, off the main thread, so the main
            // actor never blocks on a slow pasteboard server.
            let existingFilePath = item.existingFilePath
            let isPhotos = item.types.contains(.photosReferenceAsset)

            mainActor {
                self.handleClipboardChange(item: item, existingFilePath: existingFilePath, isPhotos: isPhotos, newChangeCount: newChangeCount)
            }
        }
        timer.resume()
        clipboardWatcher = timer
    }

    /// Handle a detected clipboard change on the main actor. The pasteboard was already read on the
    /// clipboard queue, so the (potentially slow) file-path resolution is passed in via
    /// `existingFilePath` rather than re-read here.
    @MainActor func handleClipboardChange(item: NSPasteboardItem, existingFilePath: FilePath?, isPhotos: Bool, newChangeCount: Int) {
        guard !pauseForNextClipboardEvent else {
            pauseForNextClipboardEvent = false
            return
        }
        guard !BM.decompressingBinaries else {
            return
        }

        scalingFactor = 1
        // Capture the app that placed this clipboard content for the `copiedBy` pipeline filter.
        OM.lastClipboardSourceApp = clipboardSourceApp(item: item)
        DebugDump.record("[clipboard] >>> handled by Clop: change #\(newChangeCount)  types=[\(item.types.map(\.rawValue).joined(separator: " "))]")

        if optimiseVideoClipboard, let path = existingFilePath, path.isVideo {
            let ignore = Defaults[.videoFormatsToSkip]
            if !ignore.isEmpty, let itemType = ItemType.from(filePath: path).utType, ignore.contains(itemType) {
                return
            }
            let alreadyOptimised = path.hasOptimisationStatusXattr()
            if alreadyOptimised {
                let type: ItemType = .video(UTType.from(filePath: path) ?? .mpeg4Movie)
                let pipelines = pipelinesFor(type: type, source: .clipboard)
                if !pipelines.isEmpty {
                    Task {
                        let optimiser = OM.optimiser(id: path.string, type: type, operation: "Running pipeline", hidden: true, source: .clipboard)
                        optimiser.url = path.url
                        await runPipelinesAfterOptimisation(file: path, type: type, source: .clipboard, optimiser: optimiser)
                    }
                }
            } else {
                Task {
                    let type: ItemType = .video(UTType.from(filePath: path) ?? .mpeg4Movie)
                    var resultPath = path
                    if let result = try? await runVideoPipeline(Video(path: path), actions: [.optimise], source: .clipboard) {
                        resultPath = result.path
                    }
                    if let optimiser = opt(path.string) {
                        await runPipelinesAfterOptimisation(file: resultPath, type: type, source: .clipboard, optimiser: optimiser)
                    }
                }
            }
            return
        }
        if Defaults[.optimisePDFClipboard], let path = existingFilePath, path.isPDF {
            let alreadyOptimised = path.hasOptimisationStatusXattr()
            if alreadyOptimised {
                let type: ItemType = .pdf
                let pipelines = pipelinesFor(type: type, source: .clipboard)
                if !pipelines.isEmpty {
                    Task {
                        let optimiser = OM.optimiser(id: path.string, type: type, operation: "Running pipeline", hidden: true, source: .clipboard)
                        optimiser.url = path.url
                        await runPipelinesAfterOptimisation(file: path, type: type, source: .clipboard, optimiser: optimiser)
                    }
                }
            } else {
                Task {
                    var resultPath = path
                    if let result = try? await runPDFPipeline(PDF(path), actions: [.optimise], source: .clipboard) {
                        resultPath = result.path
                    }
                    if let optimiser = opt(path.string) {
                        await runPipelinesAfterOptimisation(file: resultPath, type: .pdf, source: .clipboard, optimiser: optimiser)
                    }
                }
            }
            return
        }
        if existingFilePath?.isPDF ?? false {
            return
        }
        if Defaults[.optimiseAudioClipboard], let path = existingFilePath, path.isAudio {
            let ignore = Defaults[.audioFormatsToSkip]
            if !ignore.isEmpty, let itemType = ItemType.from(filePath: path).utType, ignore.contains(itemType) {
                return
            }
            let alreadyOptimised = path.hasOptimisationStatusXattr()
            if alreadyOptimised {
                let type: ItemType = .audio(UTType.from(filePath: path) ?? .mp3)
                let pipelines = pipelinesFor(type: type, source: .clipboard)
                if !pipelines.isEmpty {
                    Task {
                        let optimiser = OM.optimiser(id: path.string, type: type, operation: "Running pipeline", hidden: true, source: .clipboard)
                        optimiser.url = path.url
                        await runPipelinesAfterOptimisation(file: path, type: type, source: .clipboard, optimiser: optimiser)
                    }
                }
            } else {
                Task {
                    let type: ItemType = .audio(UTType.from(filePath: path) ?? .mp3)
                    var resultPath = path
                    if let result = try? await runAudioPipeline(Audio(path: path), actions: [.optimise], source: .clipboard) {
                        resultPath = result.path
                    }
                    if let optimiser = opt(path.string) {
                        await runPipelinesAfterOptimisation(file: resultPath, type: type, source: .clipboard, optimiser: optimiser)
                    }
                }
            }
            return
        }
        if existingFilePath?.isAudio ?? false {
            return
        }
        if isPhotos {
            optimiseClipboardPhotos()
            return
        }
        optimiseClipboardImage(item: item)
    }

    @objc func statusBarButtonClicked(_ sender: NSClickGestureRecognizer) {
        mainActor {
            if OM.skippedBecauseNotPro.isNotEmpty {
                OM.ignoreProErrorBadge = true
                sender.isEnabled = false

                guard let button = sender.view as? NSStatusBarButton else { return }
                button.performClick(self)
            }
        }
    }
}

var statusItem: NSStatusItem? {
    NSApp.windows.lazy.compactMap { window in
        window.perform(Selector(("statusItem")))?.takeUnretainedValue() as? NSStatusItem
    }.first
}

extension NSPasteboardItem {
    var existingFilePath: FilePath? {
        string(forType: .fileURL)?.fileURL?.existingFilePath ?? string(forType: .string)?.fileURL?.existingFilePath
    }
    var filePath: FilePath? {
        string(forType: .fileURL)?.fileURL?.filePath ?? string(forType: .string)?.fileURL?.filePath
    }
    var url: URL? {
        string(forType: .URL)?.url
    }
}

@MainActor func proLimitsReached(url: URL? = nil) {
    guard !Defaults[.neverShowProError] else {
        if let url, !OM.skippedBecauseNotPro.contains(url) {
            OM.skippedBecauseNotPro = OM.skippedBecauseNotPro.suffix(4).with(url)
        }
        if OM.skippedBecauseNotPro.isNotEmpty {
            let onclick = NSClickGestureRecognizer(target: AppDelegate.instance, action: #selector(AppDelegate.statusBarButtonClicked(_:)))
            statusItem?.button?.addGestureRecognizer(onclick)
        }

        return
    }

    let optimiser = OM.optimiser(id: Optimiser.IDs.pro, type: .unknown, operation: "")
    optimiser.finish(error: "You've optimised 5 files this session", notice: "Get Clop Pro to remove the limit and unlock all features.\nRelaunch the app to reset the counter.", keepFor: 5000)
}

// Stable identifiers for Clop's AppKit windows (the batch window's lives in BatchWindow.swift). Used to
// drive the activation policy by identity rather than by title, which carries the file name / tab name.
let COMPARISON_WINDOW_IDENTIFIER = NSUserInterfaceItemIdentifier("clop.comparison.window")
let ONBOARDING_WINDOW_IDENTIFIER = NSUserInterfaceItemIdentifier("clop.onboarding.window")
let CROP_WINDOW_IDENTIFIER = NSUserInterfaceItemIdentifier("clop.crop.window")

extension NSWindow {
    /// The Settings scene is declared as `Window("Settings", id: "settings")`; SwiftUI maps that
    /// scene `id` into the AppKit window identifier. Match on that instead of the title, which the
    /// navigation sidebar now overwrites with the selected tab's name. `contains` rather than `==`
    /// so we tolerate any prefix/suffix SwiftUI may wrap around the scene id.
    var isSettingsWindow: Bool {
        identifier?.rawValue.contains("settings") ?? false
    }

    /// Clop's real windows — Settings, Batch, Comparison, Onboarding, Crop — the ones that should give
    /// the app a Dock icon + Cmd-Tab entry while open (vs. the floating-result panels and the menu-bar
    /// item, which shouldn't). Matched by stable identifier, not title.
    var isActivatingAppWindow: Bool {
        if isSettingsWindow { return true }
        guard let id = identifier else { return false }
        return id == BATCH_WINDOW_IDENTIFIER
            || id == COMPARISON_WINDOW_IDENTIFIER
            || id == ONBOARDING_WINDOW_IDENTIFIER
            || id == CROP_WINDOW_IDENTIFIER
    }
}

// These two windows are app-lifetime singletons that get closed/reopened when the user toggles
// floating results or the drop zone. OSDWindow defaults to isReleasedWhenClosed = true, which would
// free the window on close() while these global `let`s still point at it, so the next access (e.g.
// `.isVisible`) reads freed memory and crashes (EXC_BAD_ACCESS). Keep them alive across close.
let floatingResultsWindow = OSDWindow(swiftuiView: FloatingResultContainer().any, releaseWhenClosed: false, level: .floating, canScreenshot: Defaults[.allowClopToAppearInScreenshots], allowsMouse: true)
let cursorDropZoneWindow = OSDWindow(swiftuiView: DropZoneView().any, releaseWhenClosed: false, level: .floating, canScreenshot: Defaults[.allowClopToAppearInScreenshots], allowsMouse: true)
var clipboardWatcher: DispatchSourceTimer?
/// Dedicated serial queue for all pasteboard polling/reads, so the (synchronous, sometimes slow)
/// pasteboard-server round-trips never run on the main thread. See `initClipboardOptimiser`.
let clipboardQueue = DispatchQueue(label: "\(Bundle.main.bundleIdentifier ?? "com.lowtechguys.Clop").clipboard")
var pbChangeCount = NSPasteboard.general.changeCount
let THUMB_SIZE = CGSize(width: 300, height: 220)

func migrateSettings() {
    guard let id = Bundle.main.bundleIdentifier else {
        return
    }

    let currentPrefs = URL.libraryDirectory
        .appendingPathComponent("Preferences")
        .appendingPathComponent(id == "com.lowtechguys.Clop-setapp" ? "com.lowtechguys.Clop-setapp.plist" : "com.lowtechguys.Clop.plist")
    let oldPrefs = URL.libraryDirectory
        .appendingPathComponent("Preferences")
        .appendingPathComponent(id == "com.lowtechguys.Clop-setapp" ? "com.lowtechguys.Clop.plist" : "com.lowtechguys.Clop-setapp.plist")

    if !FileManager.default.fileExists(atPath: currentPrefs.path), FileManager.default.fileExists(atPath: oldPrefs.path) {
        try? FileManager.default.copyItem(at: oldPrefs, to: currentPrefs)
        NSUbiquitousKeyValueStore.default.synchronize()
        restart()
    }
}

/// Seed the unified per-format `CompressionQuality` keys from the legacy aggressive/adaptive/encoder/bitrate
/// settings so existing users keep identical behaviour. Each version block runs exactly once; adding a new
/// block (for another format) never re-runs the earlier ones.
@MainActor func migrateToUnifiedCompression() {
    if Defaults[.compressionModelMigratedVersion] < 1 {
        // IMAGE: collapse the three per-format aggressive bools into one factor (any aggressive -> 64),
        // and map adaptiveImageSize onto the Adaptive tier.
        let anyAggressive = Defaults[.useAggressiveOptimisationJPEG]
            || Defaults[.useAggressiveOptimisationPNG]
            || Defaults[.useAggressiveOptimisationGIF]
        Defaults[.imageCompression] = CompressionQuality(
            tier: Defaults[.adaptiveImageSize] ? .adaptive : .custom,
            factor: anyAggressive ? COMPRESSION_FACTOR_AGGRESSIVE : COMPRESSION_FACTOR_NORMAL
        )
        Defaults[.compressionModelMigratedVersion] = 1
    }
    if Defaults[.compressionModelMigratedVersion] < 2 {
        // AUDIO: map the legacy absolute bitrate onto the factor for the current output format.
        // Negative sentinels (-1/-2 = "N steps lower than input") fall back to the default factor.
        let bitrate = Defaults[.audioBitrate]
        let factor = bitrate > 0 ? audioCompressionFactor(forBitrate: bitrate, format: Defaults[.audioFormat]) : 35
        Defaults[.audioCompression] = CompressionQuality(tier: .custom, factor: factor)
        Defaults[.compressionModelMigratedVersion] = 2
    }
    if Defaults[.compressionModelMigratedVersion] < 3 {
        // VIDEO: map the legacy encoder tier; useAggressiveOptimisationMP4 nudges the factor smaller.
        var cq = videoEncoderToCQ(Defaults[.videoEncoder])
        if Defaults[.useAggressiveOptimisationMP4], cq.tier != .lossless {
            cq = CompressionQuality(tier: .smaller, factor: COMPRESSION_FACTOR_AGGRESSIVE)
        }
        Defaults[.videoCompression] = cq
        Defaults[.compressionModelMigratedVersion] = 3
    }
    if Defaults[.compressionModelMigratedVersion] < 4 {
        /// Surface the new draggable compression button by default in place of the aggressive button.
        func withCompression(_ list: [FloatingAction]) -> [FloatingAction] {
            var l = list
            if let i = l.firstIndex(of: .aggressiveOptimisation) {
                l[i] = .compression
            } else if !l.contains(.compression) {
                l.insert(.compression, at: min(1, l.count))
            }
            var seen = Set<FloatingAction>()
            return l.filter { seen.insert($0).inserted }
        }
        Defaults[.floatingResultActions] = withCompression(Defaults[.floatingResultActions])
        Defaults[.compactResultActions] = withCompression(Defaults[.compactResultActions])
        Defaults[.compressionModelMigratedVersion] = 4
    }
    if Defaults[.compressionModelMigratedVersion] < 5 {
        // AUDIO per-format targets: map the old single output format + convert-set onto the new exclusive sets.
        // Old .mp3 output -> MP3 set; everything else (.aac, .opus, lossless, .sameAsInput) -> AAC set, so
        // lossless inputs still get compressed.
        let old = Defaults[.formatsToConvertToOutputAudio]
        if Defaults[.audioFormat] == .mp3 {
            Defaults[.formatsToConvertToMP3] = old
        } else {
            Defaults[.formatsToConvertToAAC] = old
        }
        Defaults[.compressionModelMigratedVersion] = 5
    }
}

let WINDOW_MIN_SIZE = CGSize(width: 980, height: 750)

// MARK: - ClopApp

@main
struct ClopApp: App {
    init() {
        migrateSettings()
    }

    @NSApplicationDelegateAdaptor(AppDelegate.self) var appDelegate

    @Environment(\.openWindow) var openWindow
    @Environment(\.dismiss) var dismiss
    @Environment(\.scenePhase) var scenePhase

    @AppStorage("showMenubarIcon") var showMenubarIcon = Defaults[.showMenubarIcon]
    @AppStorage("useClassicMenubarIcon") var useClassicMenubarIcon = Defaults[.useClassicMenubarIcon]
    @AppStorage("useGeometricMenubarIcon") var useGeometricMenubarIcon = Defaults[.useGeometricMenubarIcon]

    @ObservedObject var om = OM
    @ObservedObject var wm = WM

    @ObservedObject var pm = PM

    var settingsWindow: some Scene {
        let w = Window("Settings", id: "settings") {
            SettingsView()
                .frame(minWidth: WINDOW_MIN_SIZE.width, maxWidth: .infinity, minHeight: WINDOW_MIN_SIZE.height, maxHeight: .infinity)
        }
        .windowStyle(.hiddenTitleBar)
        .windowResizability(.contentMinSize)
        .commands {
            CommandGroup(replacing: .help) {}
        }

        if #available(macOS 15.0, *) {
            return w
                .windowToolbarLabelStyle(fixed: .titleAndIcon)
        } else {
            return w
        }
    }

    var body: some Scene {
        MenuBarExtra(isInserted: $showMenubarIcon, content: {
            MenuView()
        }, label: {
            let badge = !proactive && !om.ignoreProErrorBadge && om.skippedBecauseNotPro.isNotEmpty
            SwiftUI.Image(nsImage: NSImage(
                resource: badge
                    ? (useGeometricMenubarIcon ? .menubarIconBadgeGeometric : useClassicMenubarIcon ? .menubarIconBadgeClassic : .menubarIconBadge)
                    : (useGeometricMenubarIcon ? .menubarIconGeometric : useClassicMenubarIcon ? .menubarIconClassic : .menubarIcon)
            ))
        })
        .menuBarExtraStyle(.menu)
        .onChange(of: showMenubarIcon) { show in
            if !show {
                openWindow(id: "settings")
                focus()
            } else {
                NSApplication.shared.keyWindow?.close()
            }
        }
        .onChange(of: wm.windowToOpen) { window in
            guard let window else { return }
            openWindow(id: window)
            focus()
            NSApp.keyWindow?.orderFrontRegardless()
            wm.windowToOpen = nil
        }

        settingsWindow
            .handlesExternalEvents(matching: ["openSettings"])

    }
}

extension NSFilePromiseReceiver {
    static let swizzleReceivePromisedFiles: String = {
        let originalSelector = #selector(receivePromisedFiles(atDestination:options:operationQueue:reader:))
        let swizzledSelector = #selector(swizzledReceivePromisedFiles(atDestination:options:operationQueue:reader:))

        guard let originalMethod = class_getInstanceMethod(NSFilePromiseReceiver.self, originalSelector),
              let swizzledMethod = class_getInstanceMethod(NSFilePromiseReceiver.self, swizzledSelector)
        else {
            return "Swizzling NSFilePromiseReceiver.receivePromisedFiles() failed"

        }

        method_exchangeImplementations(originalMethod, swizzledMethod)
        return "Swizzled NSFilePromiseReceiver.receivePromisedFiles()"
    }()

    @objc private func swizzledReceivePromisedFiles(atDestination destinationDir: URL, options: [AnyHashable: Any] = [:], operationQueue: OperationQueue, reader: @escaping (URL, Error?) -> Void) {
        let exc = tryBlock {
            self.swizzledReceivePromisedFiles(atDestination: destinationDir, options: options, operationQueue: operationQueue, reader: reader)
        }
        guard let exc else {
            return
        }
        log.error("\(exc.description)")
    }
}

import Paddle

var PRODUCTS: [Any] {
    if let product {
        [product]
    } else {
        []
    }
}

extension NSView {
    static func swizzleDragFormation() {
        guard let NSDragDestination = NSClassFromString("NSDragDestination"),
              let originalMethod = class_getInstanceMethod(NSDragDestination, NSSelectorFromString("_draggingEntered"))
        else {
            return
        }

        let imp = method_getImplementation(originalMethod)

        method_setImplementation(originalMethod, imp_implementationWithBlock({ (self: NSDraggingInfo) in
            self.draggingFormation = .pile
            typealias MyCFunction = @convention(c) (NSDraggingInfo, Selector) -> Void
            let myImp = unsafeBitCast(imp, to: MyCFunction.self)
            return myImp(self, NSSelectorFromString("_draggingEntered"))
        } as @convention(block) (NSDraggingInfo) -> Void))
    }
}

class ContextualMenuServiceProvider: NSObject {
    @objc func stripEXIFService(_ pasteboard: NSPasteboard, userData: String?, error: AutoreleasingUnsafeMutablePointer<NSString>) {
        guard let items = pasteboard.pasteboardItems, !items.isEmpty else {
            return
        }
        for item in items.compactMap(\.existingFilePath) {
            stripExifOperationQueue.addOperation {
                item.stripExif()
            }
        }

        stripExifOperationQueue.waitUntilAllOperationsAreFinished()
    }

    @objc func optimisationService(_ pasteboard: NSPasteboard, userData: String?, error: AutoreleasingUnsafeMutablePointer<NSString>) {
        guard let items = pasteboard.pasteboardItems, !items.isEmpty else {
            return
        }

        for item in items.map(ClipboardType.fromPasteboardItem) {
            guard item != .unknown else {
                continue
            }
            Task {
                try await optimiseItem(
                    item,
                    id: item.id,
                    hideFloatingResult: false,
                    downscaleTo: nil,
                    changePlaybackSpeedBy: nil,
                    aggressiveOptimisation: nil,
                    optimisationCount: &manualOptimisationCount,
                    copyToClipboard: false,
                    source: .service
                )
            }
        }
    }
}

func defaultAppForUTI(_ uti: String) -> String? {
    guard let value = LSCopyDefaultRoleHandlerForContentType(uti as CFString, [LSRolesMask.viewer, LSRolesMask.editor]) else {
        return nil
    }
    return value.takeRetainedValue() as String
}
func setDefaultAppForUTI(_ uti: String, _ bundleID: String) -> OSStatus {
    LSSetDefaultRoleHandlerForContentType(uti as CFString, [LSRolesMask.viewer, LSRolesMask.editor], bundleID as CFString)
}
func resetDefaultPlayer() {
    if let mp4Player = defaultAppForUTI("public.mpeg-4"), mp4Player.starts(with: "com.lowtechguys.Clop") {
        _ = setDefaultAppForUTI("public.mpeg-4", "com.apple.QuickTimePlayerX")
    }
    if let movPlayer = defaultAppForUTI("com.apple.quicktime-movie"), movPlayer.starts(with: "com.lowtechguys.Clop") {
        _ = setDefaultAppForUTI("com.apple.quicktime-movie", "com.apple.QuickTimePlayerX")
    }
}
